/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.paperless_rag.tables


import com.functionaldude.paperless.jooq.paperless_rag.PaperlessRag
import com.functionaldude.paperless.jooq.paperless_rag.indexes.OAUTH2_REGISTERED_CLIENT_CLIENT_ID_IDX
import com.functionaldude.paperless.jooq.paperless_rag.keys.OAUTH2_REGISTERED_CLIENT_PKEY
import com.functionaldude.paperless.jooq.paperless_rag.tables.records.Oauth2RegisteredClientRecord
import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Oauth2RegisteredClient(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, Oauth2RegisteredClientRecord>?,
  parentPath: InverseForeignKey<out Record, Oauth2RegisteredClientRecord>?,
  aliased: Table<Oauth2RegisteredClientRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<Oauth2RegisteredClientRecord>(
  alias,
  PaperlessRag.PAPERLESS_RAG,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>paperless_rag.oauth2_registered_client</code>
     */
    val OAUTH2_REGISTERED_CLIENT: Oauth2RegisteredClient = Oauth2RegisteredClient()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<Oauth2RegisteredClientRecord> = Oauth2RegisteredClientRecord::class.java

  /**
   * The column <code>paperless_rag.oauth2_registered_client.id</code>.
   */
  val ID: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("id"), SQLDataType.VARCHAR(100).nullable(false), this, "")

  /**
   * The column <code>paperless_rag.oauth2_registered_client.client_id</code>.
   */
  val CLIENT_ID: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("client_id"), SQLDataType.VARCHAR(100).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_id_issued_at</code>.
   */
  val CLIENT_ID_ISSUED_AT: TableField<Oauth2RegisteredClientRecord, LocalDateTime?> = createField(
    DSL.name("client_id_issued_at"),
    SQLDataType.LOCALDATETIME(6).nullable(false)
      .defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)),
    this,
    ""
  )

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_secret</code>.
   */
  val CLIENT_SECRET: TableField<Oauth2RegisteredClientRecord, String?> = createField(
    DSL.name("client_secret"),
    SQLDataType.VARCHAR(200).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)),
    this,
    ""
  )

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_secret_expires_at</code>.
   */
  val CLIENT_SECRET_EXPIRES_AT: TableField<Oauth2RegisteredClientRecord, LocalDateTime?> =
    createField(DSL.name("client_secret_expires_at"), SQLDataType.LOCALDATETIME(6), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_name</code>.
   */
  val CLIENT_NAME: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("client_name"), SQLDataType.VARCHAR(200).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_authentication_methods</code>.
   */
  val CLIENT_AUTHENTICATION_METHODS: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("client_authentication_methods"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.authorization_grant_types</code>.
   */
  val AUTHORIZATION_GRANT_TYPES: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("authorization_grant_types"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.redirect_uris</code>.
   */
  val REDIRECT_URIS: TableField<Oauth2RegisteredClientRecord, String?> = createField(
    DSL.name("redirect_uris"),
    SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)),
    this,
    ""
  )

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.post_logout_redirect_uris</code>.
   */
  val POST_LOGOUT_REDIRECT_URIS: TableField<Oauth2RegisteredClientRecord, String?> = createField(
    DSL.name("post_logout_redirect_uris"),
    SQLDataType.VARCHAR(1000).defaultValue(DSL.field(DSL.raw("NULL::character varying"), SQLDataType.VARCHAR)),
    this,
    ""
  )

  /**
   * The column <code>paperless_rag.oauth2_registered_client.scopes</code>.
   */
  val SCOPES: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("scopes"), SQLDataType.VARCHAR(1000).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.client_settings</code>.
   */
  val CLIENT_SETTINGS: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("client_settings"), SQLDataType.VARCHAR(2000).nullable(false), this, "")

  /**
   * The column
   * <code>paperless_rag.oauth2_registered_client.token_settings</code>.
   */
  val TOKEN_SETTINGS: TableField<Oauth2RegisteredClientRecord, String?> =
    createField(DSL.name("token_settings"), SQLDataType.VARCHAR(2000).nullable(false), this, "")

  private constructor(alias: Name, aliased: Table<Oauth2RegisteredClientRecord>?) : this(
    alias,
    null,
    null,
    null,
    aliased,
    null,
    null
  )

  private constructor(alias: Name, aliased: Table<Oauth2RegisteredClientRecord>?, parameters: Array<Field<*>?>?) : this(
    alias,
    null,
    null,
    null,
    aliased,
    parameters,
    null
  )

  private constructor(alias: Name, aliased: Table<Oauth2RegisteredClientRecord>?, where: Condition?) : this(
    alias,
    null,
    null,
    null,
    aliased,
    null,
    where
  )

  /**
   * Create an aliased <code>paperless_rag.oauth2_registered_client</code>
   * table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>paperless_rag.oauth2_registered_client</code>
   * table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>paperless_rag.oauth2_registered_client</code> table
   * reference
   */
  constructor() : this(DSL.name("oauth2_registered_client"), null)

  override fun getSchema(): Schema? = if (aliased()) null else PaperlessRag.PAPERLESS_RAG
  override fun getIndexes(): List<Index> = listOf(OAUTH2_REGISTERED_CLIENT_CLIENT_ID_IDX)
  override fun getPrimaryKey(): UniqueKey<Oauth2RegisteredClientRecord> = OAUTH2_REGISTERED_CLIENT_PKEY
  override fun `as`(alias: String): Oauth2RegisteredClient = Oauth2RegisteredClient(DSL.name(alias), this)
  override fun `as`(alias: Name): Oauth2RegisteredClient = Oauth2RegisteredClient(alias, this)
  override fun `as`(alias: Table<*>): Oauth2RegisteredClient = Oauth2RegisteredClient(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): Oauth2RegisteredClient = Oauth2RegisteredClient(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): Oauth2RegisteredClient = Oauth2RegisteredClient(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): Oauth2RegisteredClient = Oauth2RegisteredClient(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): Oauth2RegisteredClient =
    Oauth2RegisteredClient(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): Oauth2RegisteredClient = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): Oauth2RegisteredClient = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): Oauth2RegisteredClient = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): Oauth2RegisteredClient = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): Oauth2RegisteredClient = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Oauth2RegisteredClient =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Oauth2RegisteredClient =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): Oauth2RegisteredClient = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): Oauth2RegisteredClient = where(DSL.notExists(select))
}
