/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.paperless_rag.keys


import com.functionaldude.paperless.jooq.paperless_rag.tables.DocumentChunk
import com.functionaldude.paperless.jooq.paperless_rag.tables.DocumentSource
import com.functionaldude.paperless.jooq.paperless_rag.tables.records.DocumentChunkRecord
import com.functionaldude.paperless.jooq.paperless_rag.tables.records.DocumentSourceRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal


// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val DOCUMENT_CHUNK_PKEY: UniqueKey<DocumentChunkRecord> = Internal.createUniqueKey(
  DocumentChunk.DOCUMENT_CHUNK,
  DSL.name("document_chunk_pkey"),
  arrayOf(DocumentChunk.DOCUMENT_CHUNK.ID),
  true
)
val UQ_DOCUMENT_CHUNK_DOC_IDX: UniqueKey<DocumentChunkRecord> = Internal.createUniqueKey(
  DocumentChunk.DOCUMENT_CHUNK,
  DSL.name("uq_document_chunk_doc_idx"),
  arrayOf(DocumentChunk.DOCUMENT_CHUNK.DOCUMENT_SOURCE_ID, DocumentChunk.DOCUMENT_CHUNK.CHUNK_INDEX),
  true
)
val DOCUMENT_SOURCE_PAPERLESS_DOC_ID_KEY: UniqueKey<DocumentSourceRecord> = Internal.createUniqueKey(
  DocumentSource.DOCUMENT_SOURCE,
  DSL.name("document_source_paperless_doc_id_key"),
  arrayOf(DocumentSource.DOCUMENT_SOURCE.PAPERLESS_DOC_ID),
  true
)
val DOCUMENT_SOURCE_PKEY: UniqueKey<DocumentSourceRecord> = Internal.createUniqueKey(
  DocumentSource.DOCUMENT_SOURCE,
  DSL.name("document_source_pkey"),
  arrayOf(DocumentSource.DOCUMENT_SOURCE.ID),
  true
)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val DOCUMENT_CHUNK__DOCUMENT_CHUNK_DOCUMENT_SOURCE_ID_FKEY: ForeignKey<DocumentChunkRecord, DocumentSourceRecord> =
  Internal.createForeignKey(
    DocumentChunk.DOCUMENT_CHUNK,
    DSL.name("document_chunk_document_source_id_fkey"),
    arrayOf(DocumentChunk.DOCUMENT_CHUNK.DOCUMENT_SOURCE_ID),
    com.functionaldude.paperless.jooq.paperless_rag.keys.DOCUMENT_SOURCE_PAPERLESS_DOC_ID_KEY,
    arrayOf(DocumentSource.DOCUMENT_SOURCE.PAPERLESS_DOC_ID),
    true
  )
