/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountEmailaddress(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.account_emailaddress</code>
     */
    val ACCOUNT_EMAILADDRESS: AccountEmailaddress = AccountEmailaddress()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord::class.java

  /**
   * The column <code>public.account_emailaddress.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.account_emailaddress.email</code>.
   */
  val EMAIL: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, String?> =
    createField(DSL.name("email"), SQLDataType.VARCHAR(254).nullable(false), this, "")

  /**
   * The column <code>public.account_emailaddress.verified</code>.
   */
  val VERIFIED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Boolean?> =
    createField(DSL.name("verified"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.account_emailaddress.primary</code>.
   */
  val PRIMARY: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Boolean?> =
    createField(DSL.name("primary"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.account_emailaddress.user_id</code>.
   */
  val USER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Int?> =
    createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.account_emailaddress</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.account_emailaddress</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.account_emailaddress</code> table reference
   */
  constructor() : this(DSL.name("account_emailaddress"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    ACCOUNT_EMAILADDRESS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class AccountEmailaddressPath : AccountEmailaddress,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): AccountEmailaddressPath = AccountEmailaddressPath(DSL.name(alias), this)
    override fun `as`(alias: Name): AccountEmailaddressPath = AccountEmailaddressPath(alias, this)
    override fun `as`(alias: Table<*>): AccountEmailaddressPath = AccountEmailaddressPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.ACCOUNT_EMAILADDRESS_EMAIL_03BE32B2,
    com.functionaldude.paperless.jooq.`public`.indexes.ACCOUNT_EMAILADDRESS_EMAIL_03BE32B2_LIKE,
    com.functionaldude.paperless.jooq.`public`.indexes.ACCOUNT_EMAILADDRESS_USER_ID_2C513194,
    com.functionaldude.paperless.jooq.`public`.indexes.UNIQUE_PRIMARY_EMAIL,
    com.functionaldude.paperless.jooq.`public`.indexes.UNIQUE_VERIFIED_EMAIL
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILADDRESS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILADDRESS_USER_ID_EMAIL_987C8728_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailaddressRecord, *>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILADDRESS__ACCOUNT_EMAILADDRESS_USER_ID_2C513194_FK_AUTH_USER_ID)

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILADDRESS__ACCOUNT_EMAILADDRESS_USER_ID_2C513194_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  private lateinit var _accountEmailconfirmation: com.functionaldude.paperless.jooq.`public`.tables.AccountEmailconfirmation.AccountEmailconfirmationPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.account_emailconfirmation</code> table
   */
  fun accountEmailconfirmation(): com.functionaldude.paperless.jooq.`public`.tables.AccountEmailconfirmation.AccountEmailconfirmationPath {
    if (!this::_accountEmailconfirmation.isInitialized)
      _accountEmailconfirmation =
        com.functionaldude.paperless.jooq.`public`.tables.AccountEmailconfirmation.AccountEmailconfirmationPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILCONFIRMATION__ACCOUNT_EMAILCONFIRM_EMAIL_ADDRESS_ID_5B7F8C58_FK_ACCOUNT_E.inverseKey
        )

    return _accountEmailconfirmation;
  }

  val accountEmailconfirmation: com.functionaldude.paperless.jooq.`public`.tables.AccountEmailconfirmation.AccountEmailconfirmationPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AccountEmailconfirmation.AccountEmailconfirmationPath = accountEmailconfirmation()

  override fun `as`(alias: String): AccountEmailaddress = AccountEmailaddress(DSL.name(alias), this)
  override fun `as`(alias: Name): AccountEmailaddress = AccountEmailaddress(alias, this)
  override fun `as`(alias: Table<*>): AccountEmailaddress = AccountEmailaddress(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): AccountEmailaddress = AccountEmailaddress(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): AccountEmailaddress = AccountEmailaddress(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): AccountEmailaddress = AccountEmailaddress(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): AccountEmailaddress =
    AccountEmailaddress(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): AccountEmailaddress = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): AccountEmailaddress = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): AccountEmailaddress = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): AccountEmailaddress = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): AccountEmailaddress = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AccountEmailaddress =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AccountEmailaddress =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): AccountEmailaddress = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): AccountEmailaddress = where(DSL.notExists(select))
}
