/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountEmailconfirmation(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.account_emailconfirmation</code>
     */
    val ACCOUNT_EMAILCONFIRMATION: AccountEmailconfirmation = AccountEmailconfirmation()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord::class.java

  /**
   * The column <code>public.account_emailconfirmation.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.account_emailconfirmation.created</code>.
   */
  val CREATED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, OffsetDateTime?> =
    createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.account_emailconfirmation.sent</code>.
   */
  val SENT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, OffsetDateTime?> =
    createField(DSL.name("sent"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.account_emailconfirmation.key</code>.
   */
  val KEY: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, String?> =
    createField(DSL.name("key"), SQLDataType.VARCHAR(64).nullable(false), this, "")

  /**
   * The column
   * <code>public.account_emailconfirmation.email_address_id</code>.
   */
  val EMAIL_ADDRESS_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, Int?> =
    createField(DSL.name("email_address_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.account_emailconfirmation</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.account_emailconfirmation</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.account_emailconfirmation</code> table reference
   */
  constructor() : this(DSL.name("account_emailconfirmation"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    ACCOUNT_EMAILCONFIRMATION,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class AccountEmailconfirmationPath : AccountEmailconfirmation,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): AccountEmailconfirmationPath = AccountEmailconfirmationPath(DSL.name(alias), this)
    override fun `as`(alias: Name): AccountEmailconfirmationPath = AccountEmailconfirmationPath(alias, this)
    override fun `as`(alias: Table<*>): AccountEmailconfirmationPath =
      AccountEmailconfirmationPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.ACCOUNT_EMAILCONFIRMATION_EMAIL_ADDRESS_ID_5B7F8C58,
    com.functionaldude.paperless.jooq.`public`.indexes.ACCOUNT_EMAILCONFIRMATION_KEY_F43612BD_LIKE
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILCONFIRMATION_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILCONFIRMATION_KEY_KEY)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.AccountEmailconfirmationRecord, *>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILCONFIRMATION__ACCOUNT_EMAILCONFIRM_EMAIL_ADDRESS_ID_5B7F8C58_FK_ACCOUNT_E)

  private lateinit var _accountEmailaddress: com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.AccountEmailaddressPath

  /**
   * Get the implicit join path to the
   * <code>public.account_emailaddress</code> table.
   */
  fun accountEmailaddress(): com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.AccountEmailaddressPath {
    if (!this::_accountEmailaddress.isInitialized)
      _accountEmailaddress =
        com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.AccountEmailaddressPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.ACCOUNT_EMAILCONFIRMATION__ACCOUNT_EMAILCONFIRM_EMAIL_ADDRESS_ID_5B7F8C58_FK_ACCOUNT_E,
          null
        )

    return _accountEmailaddress;
  }

  val accountEmailaddress: com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.AccountEmailaddressPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.AccountEmailaddressPath = accountEmailaddress()

  override fun `as`(alias: String): AccountEmailconfirmation = AccountEmailconfirmation(DSL.name(alias), this)
  override fun `as`(alias: Name): AccountEmailconfirmation = AccountEmailconfirmation(alias, this)
  override fun `as`(alias: Table<*>): AccountEmailconfirmation = AccountEmailconfirmation(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): AccountEmailconfirmation = AccountEmailconfirmation(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): AccountEmailconfirmation = AccountEmailconfirmation(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): AccountEmailconfirmation = AccountEmailconfirmation(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): AccountEmailconfirmation =
    AccountEmailconfirmation(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): AccountEmailconfirmation = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): AccountEmailconfirmation = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): AccountEmailconfirmation = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): AccountEmailconfirmation = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): AccountEmailconfirmation = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AccountEmailconfirmation =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AccountEmailconfirmation =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): AccountEmailconfirmation = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): AccountEmailconfirmation = where(DSL.notExists(select))
}
