/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoAdminLog(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.django_admin_log</code>
     */
    val DJANGO_ADMIN_LOG: DjangoAdminLog = DjangoAdminLog()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord::class.java

  /**
   * The column <code>public.django_admin_log.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.django_admin_log.action_time</code>.
   */
  val ACTION_TIME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, OffsetDateTime?> =
    createField(DSL.name("action_time"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.django_admin_log.object_id</code>.
   */
  val OBJECT_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, String?> =
    createField(DSL.name("object_id"), SQLDataType.CLOB, this, "")

  /**
   * The column <code>public.django_admin_log.object_repr</code>.
   */
  val OBJECT_REPR: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, String?> =
    createField(DSL.name("object_repr"), SQLDataType.VARCHAR(200).nullable(false), this, "")

  /**
   * The column <code>public.django_admin_log.action_flag</code>.
   */
  val ACTION_FLAG: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Short?> =
    createField(DSL.name("action_flag"), SQLDataType.SMALLINT.nullable(false), this, "")

  /**
   * The column <code>public.django_admin_log.change_message</code>.
   */
  val CHANGE_MESSAGE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, String?> =
    createField(DSL.name("change_message"), SQLDataType.CLOB.nullable(false), this, "")

  /**
   * The column <code>public.django_admin_log.content_type_id</code>.
   */
  val CONTENT_TYPE_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Int?> =
    createField(DSL.name("content_type_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.django_admin_log.user_id</code>.
   */
  val USER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Int?> =
    createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.django_admin_log</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.django_admin_log</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.django_admin_log</code> table reference
   */
  constructor() : this(DSL.name("django_admin_log"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DJANGO_ADMIN_LOG,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DjangoAdminLogPath : DjangoAdminLog,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DjangoAdminLogPath = DjangoAdminLogPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DjangoAdminLogPath = DjangoAdminLogPath(alias, this)
    override fun `as`(alias: Table<*>): DjangoAdminLogPath = DjangoAdminLogPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB,
    com.functionaldude.paperless.jooq.`public`.indexes.DJANGO_ADMIN_LOG_USER_ID_C564EBA6
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DJANGO_ADMIN_LOG_PKEY

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DJANGO_ADMIN_LOG__DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO,
      com.functionaldude.paperless.jooq.`public`.keys.DJANGO_ADMIN_LOG__DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK_AUTH_USER_ID
    )

  private lateinit var _djangoContentType: com.functionaldude.paperless.jooq.`public`.tables.DjangoContentType.DjangoContentTypePath

  /**
   * Get the implicit join path to the <code>public.django_content_type</code>
   * table.
   */
  fun djangoContentType(): com.functionaldude.paperless.jooq.`public`.tables.DjangoContentType.DjangoContentTypePath {
    if (!this::_djangoContentType.isInitialized)
      _djangoContentType = com.functionaldude.paperless.jooq.`public`.tables.DjangoContentType.DjangoContentTypePath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DJANGO_ADMIN_LOG__DJANGO_ADMIN_LOG_CONTENT_TYPE_ID_C4BCE8EB_FK_DJANGO_CO,
        null
      )

    return _djangoContentType;
  }

  val djangoContentType: com.functionaldude.paperless.jooq.`public`.tables.DjangoContentType.DjangoContentTypePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DjangoContentType.DjangoContentTypePath = djangoContentType()

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DJANGO_ADMIN_LOG__DJANGO_ADMIN_LOG_USER_ID_C564EBA6_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  override fun getChecks(): List<Check<com.functionaldude.paperless.jooq.`public`.tables.records.DjangoAdminLogRecord>> =
    listOf(
      Internal.createCheck(this, DSL.name("django_admin_log_action_flag_check"), "((action_flag >= 0))", true)
    )

  override fun `as`(alias: String): DjangoAdminLog = DjangoAdminLog(DSL.name(alias), this)
  override fun `as`(alias: Name): DjangoAdminLog = DjangoAdminLog(alias, this)
  override fun `as`(alias: Table<*>): DjangoAdminLog = DjangoAdminLog(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DjangoAdminLog = DjangoAdminLog(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DjangoAdminLog = DjangoAdminLog(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DjangoAdminLog = DjangoAdminLog(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DjangoAdminLog =
    DjangoAdminLog(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DjangoAdminLog = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DjangoAdminLog = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DjangoAdminLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DjangoAdminLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DjangoAdminLog = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DjangoAdminLog =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DjangoAdminLog =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DjangoAdminLog = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DjangoAdminLog = where(DSL.notExists(select))
}
