/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowactionemail(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowactionemail</code>
     */
    val DOCUMENTS_WORKFLOWACTIONEMAIL: DocumentsWorkflowactionemail = DocumentsWorkflowactionemail()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord::class.java

  /**
   * The column <code>public.documents_workflowactionemail.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_workflowactionemail.subject</code>.
   */
  val SUBJECT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, String?> =
    createField(DSL.name("subject"), SQLDataType.VARCHAR(256).nullable(false), this, "")

  /**
   * The column <code>public.documents_workflowactionemail.body</code>.
   */
  val BODY: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, String?> =
    createField(DSL.name("body"), SQLDataType.CLOB.nullable(false), this, "")

  /**
   * The column <code>public.documents_workflowactionemail.to</code>.
   */
  val TO: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, String?> =
    createField(DSL.name("to"), SQLDataType.CLOB.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowactionemail.include_document</code>.
   */
  val INCLUDE_DOCUMENT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, Boolean?> =
    createField(DSL.name("include_document"), SQLDataType.BOOLEAN.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_workflowactionemail</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_workflowactionemail</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_workflowactionemail</code> table
   * reference
   */
  constructor() : this(DSL.name("documents_workflowactionemail"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWACTIONEMAIL,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowactionemailPath : DocumentsWorkflowactionemail,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowactionemailPath =
      DocumentsWorkflowactionemailPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowactionemailPath = DocumentsWorkflowactionemailPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsWorkflowactionemailPath =
      DocumentsWorkflowactionemailPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionemailRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTIONEMAIL_PKEY

  private lateinit var _documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction</code> table
   */
  fun documentsWorkflowaction(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath {
    if (!this::_documentsWorkflowaction.isInitialized)
      _documentsWorkflowaction =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_EMAIL_ID_3B59174D_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowaction;
  }

  val documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowaction()

  override fun `as`(alias: String): DocumentsWorkflowactionemail = DocumentsWorkflowactionemail(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsWorkflowactionemail = DocumentsWorkflowactionemail(alias, this)
  override fun `as`(alias: Table<*>): DocumentsWorkflowactionemail =
    DocumentsWorkflowactionemail(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowactionemail = DocumentsWorkflowactionemail(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowactionemail = DocumentsWorkflowactionemail(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowactionemail =
    DocumentsWorkflowactionemail(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowactionemail =
    DocumentsWorkflowactionemail(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowactionemail = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowactionemail = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowactionemail = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowactionemail = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowactionemail = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflowactionemail =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsWorkflowactionemail =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowactionemail = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowactionemail = where(DSL.notExists(select))
}
