/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsCustomfieldinstance(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_customfieldinstance</code>
     */
    val DOCUMENTS_CUSTOMFIELDINSTANCE: DocumentsCustomfieldinstance = DocumentsCustomfieldinstance()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord::class.java

  /**
   * The column <code>public.documents_customfieldinstance.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.created</code>.
   */
  val CREATED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, OffsetDateTime?> =
    createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_text</code>.
   */
  val VALUE_TEXT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, String?> =
    createField(DSL.name("value_text"), SQLDataType.VARCHAR(128), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_bool</code>.
   */
  val VALUE_BOOL: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Boolean?> =
    createField(DSL.name("value_bool"), SQLDataType.BOOLEAN, this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_url</code>.
   */
  val VALUE_URL: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, String?> =
    createField(DSL.name("value_url"), SQLDataType.VARCHAR(200), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_date</code>.
   */
  val VALUE_DATE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, LocalDate?> =
    createField(DSL.name("value_date"), SQLDataType.LOCALDATE, this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_int</code>.
   */
  val VALUE_INT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?> =
    createField(DSL.name("value_int"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_customfieldinstance.value_float</code>.
   */
  val VALUE_FLOAT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Double?> =
    createField(DSL.name("value_float"), SQLDataType.DOUBLE, this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.value_monetary</code>.
   */
  val VALUE_MONETARY: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, String?> =
    createField(DSL.name("value_monetary"), SQLDataType.VARCHAR(128), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.document_id</code>.
   */
  val DOCUMENT_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?> =
    createField(DSL.name("document_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.field_id</code>.
   */
  val FIELD_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?> =
    createField(DSL.name("field_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.value_document_ids</code>.
   */
  val VALUE_DOCUMENT_IDS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, JSONB?> =
    createField(DSL.name("value_document_ids"), SQLDataType.JSONB, this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.value_select</code>.
   */
  val VALUE_SELECT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, String?> =
    createField(DSL.name("value_select"), SQLDataType.VARCHAR(16), this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.value_monetary_amount</code>.
   */
  val VALUE_MONETARY_AMOUNT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, BigDecimal?> =
    createField(DSL.name("value_monetary_amount"), SQLDataType.NUMERIC(65, 2), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.deleted_at</code>.
   */
  val DELETED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, OffsetDateTime?> =
    createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_customfieldinstance.restored_at</code>.
   */
  val RESTORED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, OffsetDateTime?> =
    createField(DSL.name("restored_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.transaction_id</code>.
   */
  val TRANSACTION_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, UUID?> =
    createField(DSL.name("transaction_id"), SQLDataType.UUID, this, "")

  /**
   * The column
   * <code>public.documents_customfieldinstance.value_long_text</code>.
   */
  val VALUE_LONG_TEXT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, String?> =
    createField(DSL.name("value_long_text"), SQLDataType.CLOB, this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_customfieldinstance</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_customfieldinstance</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_customfieldinstance</code> table
   * reference
   */
  constructor() : this(DSL.name("documents_customfieldinstance"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_CUSTOMFIELDINSTANCE,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsCustomfieldinstancePath : DocumentsCustomfieldinstance,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsCustomfieldinstancePath =
      DocumentsCustomfieldinstancePath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsCustomfieldinstancePath = DocumentsCustomfieldinstancePath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsCustomfieldinstancePath =
      DocumentsCustomfieldinstancePath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_CUSTOMFIELDINSTANCE_CREATED_75F17F1D,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_CUSTOMFIELDINSTANCE_DOCUMENT_ID_610A968E,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_CUSTOMFIELDINSTANCE_FIELD_ID_6C59E32F
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE_UNIQUE_DOCUMENT_FIELD)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldinstanceRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_DOCUMENT_ID_610A968E_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_FIELD_ID_6C59E32F_FK_DOCUMENTS
    )

  private lateinit var _documentsDocument: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath

  /**
   * Get the implicit join path to the <code>public.documents_document</code>
   * table.
   */
  fun documentsDocument(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath {
    if (!this::_documentsDocument.isInitialized)
      _documentsDocument = com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_DOCUMENT_ID_610A968E_FK_DOCUMENTS,
        null
      )

    return _documentsDocument;
  }

  val documentsDocument: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath = documentsDocument()

  private lateinit var _documentsCustomfield: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_customfield</code> table.
   */
  fun documentsCustomfield(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath {
    if (!this::_documentsCustomfield.isInitialized)
      _documentsCustomfield =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_FIELD_ID_6C59E32F_FK_DOCUMENTS,
          null
        )

    return _documentsCustomfield;
  }

  val documentsCustomfield: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath = documentsCustomfield()

  override fun `as`(alias: String): DocumentsCustomfieldinstance = DocumentsCustomfieldinstance(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsCustomfieldinstance = DocumentsCustomfieldinstance(alias, this)
  override fun `as`(alias: Table<*>): DocumentsCustomfieldinstance =
    DocumentsCustomfieldinstance(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsCustomfieldinstance = DocumentsCustomfieldinstance(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsCustomfieldinstance = DocumentsCustomfieldinstance(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsCustomfieldinstance =
    DocumentsCustomfieldinstance(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsCustomfieldinstance =
    DocumentsCustomfieldinstance(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsCustomfieldinstance = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsCustomfieldinstance = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsCustomfieldinstance = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsCustomfieldinstance = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsCustomfieldinstance = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsCustomfieldinstance =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsCustomfieldinstance =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsCustomfieldinstance = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsCustomfieldinstance = where(DSL.notExists(select))
}
