/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsCustomfield(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.documents_customfield</code>
     */
    val DOCUMENTS_CUSTOMFIELD: DocumentsCustomfield = DocumentsCustomfield()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord::class.java

  /**
   * The column <code>public.documents_customfield.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_customfield.created</code>.
   */
  val CREATED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, OffsetDateTime?> =
    createField(DSL.name("created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.documents_customfield.name</code>.
   */
  val NAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, String?> =
    createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "")

  /**
   * The column <code>public.documents_customfield.data_type</code>.
   */
  val DATA_TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, String?> =
    createField(DSL.name("data_type"), SQLDataType.VARCHAR(50).nullable(false), this, "")

  /**
   * The column <code>public.documents_customfield.extra_data</code>.
   */
  val EXTRA_DATA: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, JSONB?> =
    createField(DSL.name("extra_data"), SQLDataType.JSONB, this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_customfield</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_customfield</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_customfield</code> table reference
   */
  constructor() : this(DSL.name("documents_customfield"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_CUSTOMFIELD,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsCustomfieldPath : DocumentsCustomfield,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsCustomfieldPath = DocumentsCustomfieldPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsCustomfieldPath = DocumentsCustomfieldPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsCustomfieldPath = DocumentsCustomfieldPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> =
    listOf(com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_CUSTOMFIELD_CREATED_501EF047)

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELD_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsCustomfieldRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELD_UNIQUE_NAME)

  private lateinit var _documentsCustomfieldinstance: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_customfieldinstance</code> table
   */
  fun documentsCustomfieldinstance(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath {
    if (!this::_documentsCustomfieldinstance.isInitialized)
      _documentsCustomfieldinstance =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_FIELD_ID_6C59E32F_FK_DOCUMENTS.inverseKey
        )

    return _documentsCustomfieldinstance;
  }

  val documentsCustomfieldinstance: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath = documentsCustomfieldinstance()

  private lateinit var _documentsWorkflowactionAssignCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_custom_fields</code> table
   */
  fun documentsWorkflowactionAssignCustomFields(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath {
    if (!this::_documentsWorkflowactionAssignCustomFields.isInitialized)
      _documentsWorkflowactionAssignCustomFields =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_CUSTOMFIELD_ID_09DF9CC4_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignCustomFields;
  }

  val documentsWorkflowactionAssignCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath = documentsWorkflowactionAssignCustomFields()

  private lateinit var _documentsWorkflowactionRemoveCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_custom_fields</code> table
   */
  fun documentsWorkflowactionRemoveCustomFields(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath {
    if (!this::_documentsWorkflowactionRemoveCustomFields.isInitialized)
      _documentsWorkflowactionRemoveCustomFields =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_CUSTOMFIELD_ID_80028FE8_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveCustomFields;
  }

  val documentsWorkflowactionRemoveCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath = documentsWorkflowactionRemoveCustomFields()

  private lateinit var _documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowtrigger</code> table
   */
  fun documentsWorkflowtrigger(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath {
    if (!this::_documentsWorkflowtrigger.isInitialized)
      _documentsWorkflowtrigger =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER__DOCUMENTS_WORKFLOWTR_SCHEDULE_DATE_CUSTOM_450A569A_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowtrigger;
  }

  val documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath = documentsWorkflowtrigger()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_document</code> table
   */
  val documentsDocument: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocument.DocumentsDocumentPath = documentsCustomfieldinstance().documentsDocument()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_workflowaction</code> table, via the
   * <code>documents_workflowac_workflowaction_id_518e70e5_fk_documents</code>
   * key
   */
  val documentsWorkflowacWorkflowactionId_518e70e5FkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowactionAssignCustomFields().documentsWorkflowaction()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_workflowaction</code> table, via the
   * <code>documents_workflowac_workflowaction_id_edf3a9f1_fk_documents</code>
   * key
   */
  val documentsWorkflowacWorkflowactionIdEdf3a9f1FkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowactionRemoveCustomFields().documentsWorkflowaction()

  override fun `as`(alias: String): DocumentsCustomfield = DocumentsCustomfield(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsCustomfield = DocumentsCustomfield(alias, this)
  override fun `as`(alias: Table<*>): DocumentsCustomfield = DocumentsCustomfield(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsCustomfield = DocumentsCustomfield(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsCustomfield = DocumentsCustomfield(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsCustomfield = DocumentsCustomfield(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsCustomfield =
    DocumentsCustomfield(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsCustomfield = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsCustomfield = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsCustomfield = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsCustomfield = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsCustomfield = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsCustomfield =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsCustomfield =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsCustomfield = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsCustomfield = where(DSL.notExists(select))
}
