/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowaction(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowaction</code>
     */
    val DOCUMENTS_WORKFLOWACTION: DocumentsWorkflowaction = DocumentsWorkflowaction()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord::class.java

  /**
   * The column <code>public.documents_workflowaction.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_workflowaction.type</code>.
   */
  val TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("type"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column <code>public.documents_workflowaction.assign_title</code>.
   */
  val ASSIGN_TITLE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, String?> =
    createField(DSL.name("assign_title"), SQLDataType.CLOB, this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.assign_correspondent_id</code>.
   */
  val ASSIGN_CORRESPONDENT_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("assign_correspondent_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.assign_document_type_id</code>.
   */
  val ASSIGN_DOCUMENT_TYPE_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("assign_document_type_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_workflowaction.assign_owner_id</code>.
   */
  val ASSIGN_OWNER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("assign_owner_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.assign_storage_path_id</code>.
   */
  val ASSIGN_STORAGE_PATH_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("assign_storage_path_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_correspondents</code>.
   */
  val REMOVE_ALL_CORRESPONDENTS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_correspondents"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_custom_fields</code>.
   */
  val REMOVE_ALL_CUSTOM_FIELDS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_custom_fields"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_document_types</code>.
   */
  val REMOVE_ALL_DOCUMENT_TYPES: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_document_types"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_owners</code>.
   */
  val REMOVE_ALL_OWNERS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_owners"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_permissions</code>.
   */
  val REMOVE_ALL_PERMISSIONS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_permissions"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.remove_all_storage_paths</code>.
   */
  val REMOVE_ALL_STORAGE_PATHS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_storage_paths"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_workflowaction.remove_all_tags</code>.
   */
  val REMOVE_ALL_TAGS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Boolean?> =
    createField(DSL.name("remove_all_tags"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_workflowaction.email_id</code>.
   */
  val EMAIL_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("email_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_workflowaction.webhook_id</code>.
   */
  val WEBHOOK_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("webhook_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column
   * <code>public.documents_workflowaction.assign_custom_fields_values</code>.
   */
  val ASSIGN_CUSTOM_FIELDS_VALUES: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, JSONB?> =
    createField(DSL.name("assign_custom_fields_values"), SQLDataType.JSONB, this, "")

  /**
   * The column <code>public.documents_workflowaction.order</code>.
   */
  val ORDER: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    createField(DSL.name("order"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_workflowaction</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_workflowaction</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_workflowaction</code> table reference
   */
  constructor() : this(DSL.name("documents_workflowaction"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWACTION,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowactionPath : DocumentsWorkflowaction,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowactionPath = DocumentsWorkflowactionPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsWorkflowactionPath = DocumentsWorkflowactionPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsWorkflowactionPath =
      DocumentsWorkflowactionPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_ASSIGN_CORRESPONDENT_ID_2292447E,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_ASSIGN_DOCUMENT_TYPE_ID_4D37BD10,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_ASSIGN_OWNER_ID_A409D275,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_ASSIGN_STORAGE_PATH_ID_6FEC4231,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_EMAIL_ID_3B59174D,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_WEBHOOK_ID_1011297C
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_PKEY

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_CORRESPONDENT_2292447E_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_DOCUMENT_TYPE_4D37BD10_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_OWNER_ID_A409D275_FK_AUTH_USER,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_STORAGE_PATH__6FEC4231_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_EMAIL_ID_3B59174D_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_WEBHOOK_ID_1011297C_FK_DOCUMENTS
    )

  private lateinit var _documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_correspondent</code> table.
   */
  fun documentsCorrespondent(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath {
    if (!this::_documentsCorrespondent.isInitialized)
      _documentsCorrespondent =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_CORRESPONDENT_2292447E_FK_DOCUMENTS,
          null
        )

    return _documentsCorrespondent;
  }

  val documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath = documentsCorrespondent()

  private lateinit var _documentsDocumenttype: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath

  /**
   * Get the implicit join path to the
   * <code>public.documents_documenttype</code> table.
   */
  fun documentsDocumenttype(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath {
    if (!this::_documentsDocumenttype.isInitialized)
      _documentsDocumenttype =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_DOCUMENT_TYPE_4D37BD10_FK_DOCUMENTS,
          null
        )

    return _documentsDocumenttype;
  }

  val documentsDocumenttype: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath = documentsDocumenttype()

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_OWNER_ID_A409D275_FK_AUTH_USER,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  private lateinit var _documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_storagepath</code> table.
   */
  fun documentsStoragepath(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath {
    if (!this::_documentsStoragepath.isInitialized)
      _documentsStoragepath =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_ASSIGN_STORAGE_PATH__6FEC4231_FK_DOCUMENTS,
          null
        )

    return _documentsStoragepath;
  }

  val documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath = documentsStoragepath()

  private lateinit var _documentsWorkflowactionemail: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionemail.DocumentsWorkflowactionemailPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowactionemail</code> table.
   */
  fun documentsWorkflowactionemail(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionemail.DocumentsWorkflowactionemailPath {
    if (!this::_documentsWorkflowactionemail.isInitialized)
      _documentsWorkflowactionemail =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionemail.DocumentsWorkflowactionemailPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_EMAIL_ID_3B59174D_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowactionemail;
  }

  val documentsWorkflowactionemail: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionemail.DocumentsWorkflowactionemailPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionemail.DocumentsWorkflowactionemailPath = documentsWorkflowactionemail()

  private lateinit var _documentsWorkflowactionwebhook: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionwebhook.DocumentsWorkflowactionwebhookPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowactionwebhook</code> table.
   */
  fun documentsWorkflowactionwebhook(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionwebhook.DocumentsWorkflowactionwebhookPath {
    if (!this::_documentsWorkflowactionwebhook.isInitialized)
      _documentsWorkflowactionwebhook =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionwebhook.DocumentsWorkflowactionwebhookPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION__DOCUMENTS_WORKFLOWAC_WEBHOOK_ID_1011297C_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowactionwebhook;
  }

  val documentsWorkflowactionwebhook: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionwebhook.DocumentsWorkflowactionwebhookPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionwebhook.DocumentsWorkflowactionwebhookPath = documentsWorkflowactionwebhook()

  private lateinit var _documentsWorkflowActions: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflow_actions</code> table
   */
  fun documentsWorkflowActions(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath {
    if (!this::_documentsWorkflowActions.isInitialized)
      _documentsWorkflowActions =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOW_ACTIONS__DOCUMENTS_WORKFLOW_A_WORKFLOWACTION_ID_7ED6A4FA_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowActions;
  }

  val documentsWorkflowActions: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath = documentsWorkflowActions()

  private lateinit var _documentsWorkflowactionAssignChangeGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeGroups.DocumentsWorkflowactionAssignChangeGroupsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_change_groups</code> table
   */
  fun documentsWorkflowactionAssignChangeGroups(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeGroups.DocumentsWorkflowactionAssignChangeGroupsPath {
    if (!this::_documentsWorkflowactionAssignChangeGroups.isInitialized)
      _documentsWorkflowactionAssignChangeGroups =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeGroups.DocumentsWorkflowactionAssignChangeGroupsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CHANGE_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_03784A7E_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignChangeGroups;
  }

  val documentsWorkflowactionAssignChangeGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeGroups.DocumentsWorkflowactionAssignChangeGroupsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeGroups.DocumentsWorkflowactionAssignChangeGroupsPath = documentsWorkflowactionAssignChangeGroups()

  private lateinit var _documentsWorkflowactionRemoveStoragePaths: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveStoragePaths.DocumentsWorkflowactionRemoveStoragePathsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_storage_paths</code> table
   */
  fun documentsWorkflowactionRemoveStoragePaths(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveStoragePaths.DocumentsWorkflowactionRemoveStoragePathsPath {
    if (!this::_documentsWorkflowactionRemoveStoragePaths.isInitialized)
      _documentsWorkflowactionRemoveStoragePaths =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveStoragePaths.DocumentsWorkflowactionRemoveStoragePathsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_STORAGE_PATHS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_1B269578_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveStoragePaths;
  }

  val documentsWorkflowactionRemoveStoragePaths: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveStoragePaths.DocumentsWorkflowactionRemoveStoragePathsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveStoragePaths.DocumentsWorkflowactionRemoveStoragePathsPath = documentsWorkflowactionRemoveStoragePaths()

  private lateinit var _documentsWorkflowactionRemoveOwners: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveOwners.DocumentsWorkflowactionRemoveOwnersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_owners</code> table
   */
  fun documentsWorkflowactionRemoveOwners(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveOwners.DocumentsWorkflowactionRemoveOwnersPath {
    if (!this::_documentsWorkflowactionRemoveOwners.isInitialized)
      _documentsWorkflowactionRemoveOwners =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveOwners.DocumentsWorkflowactionRemoveOwnersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_OWNERS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_27560D24_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveOwners;
  }

  val documentsWorkflowactionRemoveOwners: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveOwners.DocumentsWorkflowactionRemoveOwnersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveOwners.DocumentsWorkflowactionRemoveOwnersPath = documentsWorkflowactionRemoveOwners()

  private lateinit var _documentsWorkflowactionRemoveViewUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewUsers.DocumentsWorkflowactionRemoveViewUsersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_view_users</code> table
   */
  fun documentsWorkflowactionRemoveViewUsers(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewUsers.DocumentsWorkflowactionRemoveViewUsersPath {
    if (!this::_documentsWorkflowactionRemoveViewUsers.isInitialized)
      _documentsWorkflowactionRemoveViewUsers =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewUsers.DocumentsWorkflowactionRemoveViewUsersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_USERS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_4AA554C0_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveViewUsers;
  }

  val documentsWorkflowactionRemoveViewUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewUsers.DocumentsWorkflowactionRemoveViewUsersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewUsers.DocumentsWorkflowactionRemoveViewUsersPath = documentsWorkflowactionRemoveViewUsers()

  private lateinit var _documentsWorkflowactionRemoveCorrespondents: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCorrespondents.DocumentsWorkflowactionRemoveCorrespondentsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_correspondents</code> table
   */
  fun documentsWorkflowactionRemoveCorrespondents(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCorrespondents.DocumentsWorkflowactionRemoveCorrespondentsPath {
    if (!this::_documentsWorkflowactionRemoveCorrespondents.isInitialized)
      _documentsWorkflowactionRemoveCorrespondents =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCorrespondents.DocumentsWorkflowactionRemoveCorrespondentsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_CORRESPONDENTS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_4EC66E2F_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveCorrespondents;
  }

  val documentsWorkflowactionRemoveCorrespondents: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCorrespondents.DocumentsWorkflowactionRemoveCorrespondentsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCorrespondents.DocumentsWorkflowactionRemoveCorrespondentsPath = documentsWorkflowactionRemoveCorrespondents()

  private lateinit var _documentsWorkflowactionAssignCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_custom_fields</code> table
   */
  fun documentsWorkflowactionAssignCustomFields(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath {
    if (!this::_documentsWorkflowactionAssignCustomFields.isInitialized)
      _documentsWorkflowactionAssignCustomFields =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_518E70E5_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignCustomFields;
  }

  val documentsWorkflowactionAssignCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignCustomFields.DocumentsWorkflowactionAssignCustomFieldsPath = documentsWorkflowactionAssignCustomFields()

  private lateinit var _documentsWorkflowactionRemoveChangeGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeGroups.DocumentsWorkflowactionRemoveChangeGroupsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_change_groups</code> table
   */
  fun documentsWorkflowactionRemoveChangeGroups(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeGroups.DocumentsWorkflowactionRemoveChangeGroupsPath {
    if (!this::_documentsWorkflowactionRemoveChangeGroups.isInitialized)
      _documentsWorkflowactionRemoveChangeGroups =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeGroups.DocumentsWorkflowactionRemoveChangeGroupsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_CHANGE_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_6629046F_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveChangeGroups;
  }

  val documentsWorkflowactionRemoveChangeGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeGroups.DocumentsWorkflowactionRemoveChangeGroupsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeGroups.DocumentsWorkflowactionRemoveChangeGroupsPath = documentsWorkflowactionRemoveChangeGroups()

  private lateinit var _documentsWorkflowactionAssignViewUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewUsers.DocumentsWorkflowactionAssignViewUsersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_view_users</code> table
   */
  fun documentsWorkflowactionAssignViewUsers(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewUsers.DocumentsWorkflowactionAssignViewUsersPath {
    if (!this::_documentsWorkflowactionAssignViewUsers.isInitialized)
      _documentsWorkflowactionAssignViewUsers =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewUsers.DocumentsWorkflowactionAssignViewUsersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_VIEW_USERS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_79B5B0B4_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignViewUsers;
  }

  val documentsWorkflowactionAssignViewUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewUsers.DocumentsWorkflowactionAssignViewUsersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewUsers.DocumentsWorkflowactionAssignViewUsersPath = documentsWorkflowactionAssignViewUsers()

  private lateinit var _documentsWorkflowactionRemoveViewGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewGroups.DocumentsWorkflowactionRemoveViewGroupsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_view_groups</code> table
   */
  fun documentsWorkflowactionRemoveViewGroups(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewGroups.DocumentsWorkflowactionRemoveViewGroupsPath {
    if (!this::_documentsWorkflowactionRemoveViewGroups.isInitialized)
      _documentsWorkflowactionRemoveViewGroups =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewGroups.DocumentsWorkflowactionRemoveViewGroupsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_8C532B6C_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveViewGroups;
  }

  val documentsWorkflowactionRemoveViewGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewGroups.DocumentsWorkflowactionRemoveViewGroupsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveViewGroups.DocumentsWorkflowactionRemoveViewGroupsPath = documentsWorkflowactionRemoveViewGroups()

  private lateinit var _documentsWorkflowactionRemoveTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DocumentsWorkflowactionRemoveTagsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_tags</code> table
   */
  fun documentsWorkflowactionRemoveTags(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DocumentsWorkflowactionRemoveTagsPath {
    if (!this::_documentsWorkflowactionRemoveTags.isInitialized)
      _documentsWorkflowactionRemoveTags =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DocumentsWorkflowactionRemoveTagsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_TAGS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_921C52C0_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveTags;
  }

  val documentsWorkflowactionRemoveTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DocumentsWorkflowactionRemoveTagsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DocumentsWorkflowactionRemoveTagsPath = documentsWorkflowactionRemoveTags()

  private lateinit var _documentsWorkflowactionAssignChangeUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeUsers.DocumentsWorkflowactionAssignChangeUsersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_change_users</code> table
   */
  fun documentsWorkflowactionAssignChangeUsers(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeUsers.DocumentsWorkflowactionAssignChangeUsersPath {
    if (!this::_documentsWorkflowactionAssignChangeUsers.isInitialized)
      _documentsWorkflowactionAssignChangeUsers =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeUsers.DocumentsWorkflowactionAssignChangeUsersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CHANGE_USERS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_BCC0465A_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignChangeUsers;
  }

  val documentsWorkflowactionAssignChangeUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeUsers.DocumentsWorkflowactionAssignChangeUsersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignChangeUsers.DocumentsWorkflowactionAssignChangeUsersPath = documentsWorkflowactionAssignChangeUsers()

  private lateinit var _documentsWorkflowactionRemoveChangeUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeUsers.DocumentsWorkflowactionRemoveChangeUsersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_change_users</code> table
   */
  fun documentsWorkflowactionRemoveChangeUsers(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeUsers.DocumentsWorkflowactionRemoveChangeUsersPath {
    if (!this::_documentsWorkflowactionRemoveChangeUsers.isInitialized)
      _documentsWorkflowactionRemoveChangeUsers =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeUsers.DocumentsWorkflowactionRemoveChangeUsersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_CHANGE_USERS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_BEAE1E27_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveChangeUsers;
  }

  val documentsWorkflowactionRemoveChangeUsers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeUsers.DocumentsWorkflowactionRemoveChangeUsersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveChangeUsers.DocumentsWorkflowactionRemoveChangeUsersPath = documentsWorkflowactionRemoveChangeUsers()

  private lateinit var _documentsWorkflowactionAssignTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignTags.DocumentsWorkflowactionAssignTagsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_tags</code> table
   */
  fun documentsWorkflowactionAssignTags(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignTags.DocumentsWorkflowactionAssignTagsPath {
    if (!this::_documentsWorkflowactionAssignTags.isInitialized)
      _documentsWorkflowactionAssignTags =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignTags.DocumentsWorkflowactionAssignTagsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_TAGS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_CC9EF2DA_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignTags;
  }

  val documentsWorkflowactionAssignTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignTags.DocumentsWorkflowactionAssignTagsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignTags.DocumentsWorkflowactionAssignTagsPath = documentsWorkflowactionAssignTags()

  private lateinit var _documentsWorkflowactionRemoveDocumentTypes: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveDocumentTypes.DocumentsWorkflowactionRemoveDocumentTypesPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_document_types</code> table
   */
  fun documentsWorkflowactionRemoveDocumentTypes(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveDocumentTypes.DocumentsWorkflowactionRemoveDocumentTypesPath {
    if (!this::_documentsWorkflowactionRemoveDocumentTypes.isInitialized)
      _documentsWorkflowactionRemoveDocumentTypes =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveDocumentTypes.DocumentsWorkflowactionRemoveDocumentTypesPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_DOCUMENT_TYPES__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_D80BD370_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveDocumentTypes;
  }

  val documentsWorkflowactionRemoveDocumentTypes: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveDocumentTypes.DocumentsWorkflowactionRemoveDocumentTypesPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveDocumentTypes.DocumentsWorkflowactionRemoveDocumentTypesPath = documentsWorkflowactionRemoveDocumentTypes()

  private lateinit var _documentsWorkflowactionRemoveCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_remove_custom_fields</code> table
   */
  fun documentsWorkflowactionRemoveCustomFields(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath {
    if (!this::_documentsWorkflowactionRemoveCustomFields.isInitialized)
      _documentsWorkflowactionRemoveCustomFields =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_EDF3A9F1_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionRemoveCustomFields;
  }

  val documentsWorkflowactionRemoveCustomFields: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveCustomFields.DocumentsWorkflowactionRemoveCustomFieldsPath = documentsWorkflowactionRemoveCustomFields()

  private lateinit var _documentsWorkflowactionAssignViewGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewGroups.DocumentsWorkflowactionAssignViewGroupsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowaction_assign_view_groups</code> table
   */
  fun documentsWorkflowactionAssignViewGroups(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewGroups.DocumentsWorkflowactionAssignViewGroupsPath {
    if (!this::_documentsWorkflowactionAssignViewGroups.isInitialized)
      _documentsWorkflowactionAssignViewGroups =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewGroups.DocumentsWorkflowactionAssignViewGroupsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_F8EF83C1_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowactionAssignViewGroups;
  }

  val documentsWorkflowactionAssignViewGroups: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewGroups.DocumentsWorkflowactionAssignViewGroupsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionAssignViewGroups.DocumentsWorkflowactionAssignViewGroupsPath = documentsWorkflowactionAssignViewGroups()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_workflow</code> table
   */
  val documentsWorkflow: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflow.DocumentsWorkflowPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflow.DocumentsWorkflowPath = documentsWorkflowActions().documentsWorkflow()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_group</code> table, via the
   * <code>documents_workflowac_group_id_a6d3bc2c_fk_auth_grou</code> key
   */
  val documentsWorkflowacGroupIdA6d3bc2cFkAuthGrou: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath = documentsWorkflowactionAssignChangeGroups().authGroup()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_user</code> table, via the
   * <code>documents_workflowac_user_id_73bec49c_fk_auth_user</code> key
   */
  val documentsWorkflowacUserId_73bec49cFkAuthUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = documentsWorkflowactionAssignChangeUsers().authUser()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_customfield</code> table, via the
   * <code>documents_workflowac_customfield_id_09df9cc4_fk_documents</code>
   * key
   */
  val documentsWorkflowacCustomfieldId_09df9cc4FkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath = documentsWorkflowactionAssignCustomFields().documentsCustomfield()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_tag</code> table, via the
   * <code>documents_workflowac_tag_id_6770cb84_fk_documents</code> key
   */
  val documentsWorkflowacTagId_6770cb84FkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath = documentsWorkflowactionAssignTags().documentsTag()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_group</code> table, via the
   * <code>documents_workflowac_group_id_0ff4e812_fk_auth_grou</code> key
   */
  val documentsWorkflowacGroupId_0ff4e812FkAuthGrou: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath = documentsWorkflowactionAssignViewGroups().authGroup()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_user</code> table, via the
   * <code>documents_workflowac_user_id_24b6d448_fk_auth_user</code> key
   */
  val documentsWorkflowacUserId_24b6d448FkAuthUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = documentsWorkflowactionAssignViewUsers().authUser()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_group</code> table, via the
   * <code>documents_workflowac_group_id_905a1a61_fk_auth_grou</code> key
   */
  val documentsWorkflowacGroupId_905a1a61FkAuthGrou: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath = documentsWorkflowactionRemoveChangeGroups().authGroup()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_user</code> table, via the
   * <code>documents_workflowac_user_id_ff94707a_fk_auth_user</code> key
   */
  val documentsWorkflowacUserIdFf94707aFkAuthUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = documentsWorkflowactionRemoveChangeUsers().authUser()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_customfield</code> table, via the
   * <code>documents_workflowac_customfield_id_80028fe8_fk_documents</code>
   * key
   */
  val documentsWorkflowacCustomfieldId_80028fe8FkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath = documentsWorkflowactionRemoveCustomFields().documentsCustomfield()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_user</code> table, via the
   * <code>documents_workflowac_user_id_b9cd308d_fk_auth_user</code> key
   */
  val documentsWorkflowacUserIdB9cd308dFkAuthUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = documentsWorkflowactionRemoveOwners().authUser()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_tag</code> table, via the
   * <code>documents_workflowac_tag_id_981465ff_fk_documents</code> key
   */
  val documentsWorkflowacTagId_981465ffFkDocuments: com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath = documentsWorkflowactionRemoveTags().documentsTag()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_group</code> table, via the
   * <code>documents_workflowac_group_id_43f07529_fk_auth_grou</code> key
   */
  val documentsWorkflowacGroupId_43f07529FkAuthGrou: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath = documentsWorkflowactionRemoveViewGroups().authGroup()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.auth_user</code> table, via the
   * <code>documents_workflowac_user_id_1939732e_fk_auth_user</code> key
   */
  val documentsWorkflowacUserId_1939732eFkAuthUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = documentsWorkflowactionRemoveViewUsers().authUser()

  override fun getChecks(): List<Check<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRecord>> =
    listOf(
      Internal.createCheck(this, DSL.name("documents_workflowaction_order_check"), "((\"order\" >= 0))", true),
      Internal.createCheck(this, DSL.name("documents_workflowaction_type_check"), "((type >= 0))", true)
    )

  override fun `as`(alias: String): DocumentsWorkflowaction = DocumentsWorkflowaction(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsWorkflowaction = DocumentsWorkflowaction(alias, this)
  override fun `as`(alias: Table<*>): DocumentsWorkflowaction = DocumentsWorkflowaction(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowaction = DocumentsWorkflowaction(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowaction = DocumentsWorkflowaction(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowaction = DocumentsWorkflowaction(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowaction =
    DocumentsWorkflowaction(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowaction = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowaction = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowaction = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowaction = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowaction = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflowaction =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsWorkflowaction =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowaction = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowaction = where(DSL.notExists(select))
}
