/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import java.time.LocalDate
import java.time.OffsetDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Check
import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsDocument(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.documents_document</code>
     */
    val DOCUMENTS_DOCUMENT: DocumentsDocument = DocumentsDocument()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord::class.java

  /**
   * The column <code>public.documents_document.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_document.title</code>.
   */
  val TITLE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("title"), SQLDataType.VARCHAR(128).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.content</code>.
   */
  val CONTENT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

  /**
   * The column <code>public.documents_document.modified</code>.
   */
  val MODIFIED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, OffsetDateTime?> =
    createField(DSL.name("modified"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.correspondent_id</code>.
   */
  val CORRESPONDENT_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("correspondent_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.checksum</code>.
   */
  val CHECKSUM: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("checksum"), SQLDataType.VARCHAR(32).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.added</code>.
   */
  val ADDED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, OffsetDateTime?> =
    createField(DSL.name("added"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.storage_type</code>.
   */
  val STORAGE_TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("storage_type"), SQLDataType.VARCHAR(11).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.filename</code>.
   */
  val FILENAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("filename"), SQLDataType.VARCHAR(1024), this, "")

  /**
   * The column <code>public.documents_document.archive_serial_number</code>.
   */
  val ARCHIVE_SERIAL_NUMBER: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("archive_serial_number"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.document_type_id</code>.
   */
  val DOCUMENT_TYPE_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("document_type_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.mime_type</code>.
   */
  val MIME_TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("mime_type"), SQLDataType.VARCHAR(256).nullable(false), this, "")

  /**
   * The column <code>public.documents_document.archive_checksum</code>.
   */
  val ARCHIVE_CHECKSUM: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("archive_checksum"), SQLDataType.VARCHAR(32), this, "")

  /**
   * The column <code>public.documents_document.archive_filename</code>.
   */
  val ARCHIVE_FILENAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("archive_filename"), SQLDataType.VARCHAR(1024), this, "")

  /**
   * The column <code>public.documents_document.storage_path_id</code>.
   */
  val STORAGE_PATH_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("storage_path_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.original_filename</code>.
   */
  val ORIGINAL_FILENAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, String?> =
    createField(DSL.name("original_filename"), SQLDataType.VARCHAR(1024), this, "")

  /**
   * The column <code>public.documents_document.owner_id</code>.
   */
  val OWNER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.deleted_at</code>.
   */
  val DELETED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, OffsetDateTime?> =
    createField(DSL.name("deleted_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_document.restored_at</code>.
   */
  val RESTORED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, OffsetDateTime?> =
    createField(DSL.name("restored_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_document.transaction_id</code>.
   */
  val TRANSACTION_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, UUID?> =
    createField(DSL.name("transaction_id"), SQLDataType.UUID, this, "")

  /**
   * The column <code>public.documents_document.page_count</code>.
   */
  val PAGE_COUNT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    createField(DSL.name("page_count"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_document.created</code>.
   */
  val CREATED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, LocalDate?> =
    createField(DSL.name("created"), SQLDataType.LOCALDATE.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_document</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_document</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_document</code> table reference
   */
  constructor() : this(DSL.name("documents_document"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_DOCUMENT,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsDocumentPath : DocumentsDocument,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsDocumentPath = DocumentsDocumentPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsDocumentPath = DocumentsDocumentPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsDocumentPath = DocumentsDocumentPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_ADDED_28CFA360,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_ARCHIVE_FILENAME_FC3CB023_LIKE,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_CHECKSUM_75209391_LIKE,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_CREATED_BEDD0818,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_DOCUMENT_TYPE_ID_1F88B50C,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_FILENAME_3EE5AD97_LIKE,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_MODIFIED_2EAE15BC,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_OWNER_ID_04D2B723,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_SENDER_ID_950512B2,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_STORAGE_PATH_ID_07D27BDB,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_TITLE_6B08E02A,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_DOCUMENT_TITLE_6B08E02A_LIKE
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_ARCHIVE_FILENAME_KEY,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_ARCHIVE_SERIAL_NUMBER_KEY,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_CHECKSUM_75209391_UNIQ,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_FILENAME_3EE5AD97_UNIQ
    )

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_CORRESPONDENT_ID_6164EB0C_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_DOCUMENT_TYPE_ID_1F88B50C_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_OWNER_ID_04D2B723_FK_AUTH_USER_ID,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_STORAGE_PATH_ID_07D27BDB_FK_DOCUMENTS
    )

  private lateinit var _documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_correspondent</code> table.
   */
  fun documentsCorrespondent(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath {
    if (!this::_documentsCorrespondent.isInitialized)
      _documentsCorrespondent =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_CORRESPONDENT_ID_6164EB0C_FK_DOCUMENTS,
          null
        )

    return _documentsCorrespondent;
  }

  val documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath = documentsCorrespondent()

  private lateinit var _documentsDocumenttype: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath

  /**
   * Get the implicit join path to the
   * <code>public.documents_documenttype</code> table.
   */
  fun documentsDocumenttype(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath {
    if (!this::_documentsDocumenttype.isInitialized)
      _documentsDocumenttype =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_DOCUMENT_TYPE_ID_1F88B50C_FK_DOCUMENTS,
          null
        )

    return _documentsDocumenttype;
  }

  val documentsDocumenttype: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumenttype.DocumentsDocumenttypePath = documentsDocumenttype()

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_OWNER_ID_04D2B723_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  private lateinit var _documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_storagepath</code> table.
   */
  fun documentsStoragepath(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath {
    if (!this::_documentsStoragepath.isInitialized)
      _documentsStoragepath =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT__DOCUMENTS_DOCUMENT_STORAGE_PATH_ID_07D27BDB_FK_DOCUMENTS,
          null
        )

    return _documentsStoragepath;
  }

  val documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath = documentsStoragepath()

  private lateinit var _documentsCustomfieldinstance: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_customfieldinstance</code> table
   */
  fun documentsCustomfieldinstance(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath {
    if (!this::_documentsCustomfieldinstance.isInitialized)
      _documentsCustomfieldinstance =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_CUSTOMFIELDINSTANCE__DOCUMENTS_CUSTOMFIEL_DOCUMENT_ID_610A968E_FK_DOCUMENTS.inverseKey
        )

    return _documentsCustomfieldinstance;
  }

  val documentsCustomfieldinstance: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfieldinstance.DocumentsCustomfieldinstancePath = documentsCustomfieldinstance()

  private lateinit var _documentsDocumentTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumentTags.DocumentsDocumentTagsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_document_tags</code> table
   */
  fun documentsDocumentTags(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumentTags.DocumentsDocumentTagsPath {
    if (!this::_documentsDocumentTags.isInitialized)
      _documentsDocumentTags =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumentTags.DocumentsDocumentTagsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_DOCUMENT_TAGS__DOCUMENTS_DOCUMENT_T_DOCUMENT_ID_006F35A8_FK_DOCUMENTS.inverseKey
        )

    return _documentsDocumentTags;
  }

  val documentsDocumentTags: com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumentTags.DocumentsDocumentTagsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsDocumentTags.DocumentsDocumentTagsPath = documentsDocumentTags()

  private lateinit var _documentsNote: com.functionaldude.paperless.jooq.`public`.tables.DocumentsNote.DocumentsNotePath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_note</code> table
   */
  fun documentsNote(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsNote.DocumentsNotePath {
    if (!this::_documentsNote.isInitialized)
      _documentsNote = com.functionaldude.paperless.jooq.`public`.tables.DocumentsNote.DocumentsNotePath(
        this,
        null,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_NOTE__DOCUMENTS_NOTE_DOCUMENT_ID_EF90A624_FK_DOCUMENTS_DOCUMENT_ID.inverseKey
      )

    return _documentsNote;
  }

  val documentsNote: com.functionaldude.paperless.jooq.`public`.tables.DocumentsNote.DocumentsNotePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsNote.DocumentsNotePath = documentsNote()

  private lateinit var _documentsSharelink: com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DocumentsSharelinkPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_sharelink</code> table
   */
  fun documentsSharelink(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DocumentsSharelinkPath {
    if (!this::_documentsSharelink.isInitialized)
      _documentsSharelink = com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DocumentsSharelinkPath(
        this,
        null,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_SHARELINK__DOCUMENTS_SHARELINK_DOCUMENT_ID_1BE5AB03_FK_DOCUMENTS.inverseKey
      )

    return _documentsSharelink;
  }

  val documentsSharelink: com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DocumentsSharelinkPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DocumentsSharelinkPath = documentsSharelink()

  private lateinit var _documentsWorkflowrun: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowrun</code> table
   */
  fun documentsWorkflowrun(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath {
    if (!this::_documentsWorkflowrun.isInitialized)
      _documentsWorkflowrun =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWRUN__DOCUMENTS_WORKFLOWRU_DOCUMENT_ID_DC6F429B_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowrun;
  }

  val documentsWorkflowrun: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath = documentsWorkflowrun()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_customfield</code> table
   */
  val documentsCustomfield: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath = documentsCustomfieldinstance().documentsCustomfield()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_tag</code> table
   */
  val documentsTag: com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath = documentsDocumentTags().documentsTag()

  override fun getChecks(): List<Check<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsDocumentRecord>> =
    listOf(
      Internal.createCheck(
        this,
        DSL.name("documents_document_archive_serial_number_550aa63f_check"),
        "((archive_serial_number >= 0))",
        true
      ),
      Internal.createCheck(this, DSL.name("documents_document_page_count_check"), "((page_count >= 0))", true)
    )

  override fun `as`(alias: String): DocumentsDocument = DocumentsDocument(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsDocument = DocumentsDocument(alias, this)
  override fun `as`(alias: Table<*>): DocumentsDocument = DocumentsDocument(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsDocument = DocumentsDocument(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsDocument = DocumentsDocument(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsDocument = DocumentsDocument(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsDocument =
    DocumentsDocument(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsDocument = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsDocument = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsDocument = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsDocument = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsDocument = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsDocument =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsDocument =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsDocument = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsDocument = where(DSL.notExists(select))
}
