/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowtriggerFilterHasAllTags(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowtrigger_filter_has_all_tags</code>
     */
    val DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS: DocumentsWorkflowtriggerFilterHasAllTags =
      DocumentsWorkflowtriggerFilterHasAllTags()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord::class.java

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_all_tags.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_all_tags.workflowtrigger_id</code>.
   */
  val WORKFLOWTRIGGER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, Int?> =
    createField(DSL.name("workflowtrigger_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_all_tags.tag_id</code>.
   */
  val TAG_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, Int?> =
    createField(DSL.name("tag_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_all_tags</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_all_tags</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a
   * <code>public.documents_workflowtrigger_filter_has_all_tags</code> table
   * reference
   */
  constructor() : this(DSL.name("documents_workflowtrigger_filter_has_all_tags"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowtriggerFilterHasAllTagsPath : DocumentsWorkflowtriggerFilterHasAllTags,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasAllTagsPath =
      DocumentsWorkflowtriggerFilterHasAllTagsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasAllTagsPath =
      DocumentsWorkflowtriggerFilterHasAllTagsPath(alias, this)

    override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasAllTagsPath =
      DocumentsWorkflowtriggerFilterHasAllTagsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER__WORKFLOWTRIGGER_ID_DA8DC5D4,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS_TAG_ID_DE7224C0
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGE_WORKFLOWTRIGGER_ID_TAG_I_6E2B6462_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAllTagsRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS__DOCUMENTS_WORKFLOWTR_TAG_ID_DE7224C0_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_DA8DC5D4_FK_DOCUMENTS
    )

  private lateinit var _documentsTag: com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath

  /**
   * Get the implicit join path to the <code>public.documents_tag</code>
   * table.
   */
  fun documentsTag(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath {
    if (!this::_documentsTag.isInitialized)
      _documentsTag = com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS__DOCUMENTS_WORKFLOWTR_TAG_ID_DE7224C0_FK_DOCUMENTS,
        null
      )

    return _documentsTag;
  }

  val documentsTag: com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DocumentsTagPath = documentsTag()

  private lateinit var _documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowtrigger</code> table.
   */
  fun documentsWorkflowtrigger(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath {
    if (!this::_documentsWorkflowtrigger.isInitialized)
      _documentsWorkflowtrigger =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ALL_TAGS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_DA8DC5D4_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowtrigger;
  }

  val documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath = documentsWorkflowtrigger()

  override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(DSL.name(alias), this)

  override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(alias, this)

  override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowtriggerFilterHasAllTags =
    DocumentsWorkflowtriggerFilterHasAllTags(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowtriggerFilterHasAllTags = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart
  ): DocumentsWorkflowtriggerFilterHasAllTags = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasAllTags = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasAllTags =
    where(DSL.notExists(select))
}
