/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsSavedview(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.documents_savedview</code>
     */
    val DOCUMENTS_SAVEDVIEW: DocumentsSavedview = DocumentsSavedview()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord::class.java

  /**
   * The column <code>public.documents_savedview.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_savedview.name</code>.
   */
  val NAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, String?> =
    createField(DSL.name("name"), SQLDataType.VARCHAR(128).nullable(false), this, "")

  /**
   * The column <code>public.documents_savedview.show_on_dashboard</code>.
   */
  val SHOW_ON_DASHBOARD: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Boolean?> =
    createField(DSL.name("show_on_dashboard"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_savedview.show_in_sidebar</code>.
   */
  val SHOW_IN_SIDEBAR: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Boolean?> =
    createField(DSL.name("show_in_sidebar"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_savedview.sort_field</code>.
   */
  val SORT_FIELD: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, String?> =
    createField(DSL.name("sort_field"), SQLDataType.VARCHAR(128), this, "")

  /**
   * The column <code>public.documents_savedview.sort_reverse</code>.
   */
  val SORT_REVERSE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Boolean?> =
    createField(DSL.name("sort_reverse"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_savedview.owner_id</code>.
   */
  val OWNER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Int?> =
    createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_savedview.display_mode</code>.
   */
  val DISPLAY_MODE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, String?> =
    createField(DSL.name("display_mode"), SQLDataType.VARCHAR(128), this, "")

  /**
   * The column <code>public.documents_savedview.page_size</code>.
   */
  val PAGE_SIZE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Int?> =
    createField(DSL.name("page_size"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_savedview.display_fields</code>.
   */
  val DISPLAY_FIELDS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, JSONB?> =
    createField(DSL.name("display_fields"), SQLDataType.JSONB, this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_savedview</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_savedview</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_savedview</code> table reference
   */
  constructor() : this(DSL.name("documents_savedview"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_SAVEDVIEW,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsSavedviewPath : DocumentsSavedview,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsSavedviewPath = DocumentsSavedviewPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsSavedviewPath = DocumentsSavedviewPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsSavedviewPath = DocumentsSavedviewPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> =
    listOf(com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_SAVEDVIEW_USER_ID_48BAF272)

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_SAVEDVIEW_PKEY

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord, *>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_SAVEDVIEW__DOCUMENTS_SAVEDVIEW_OWNER_ID_2DF222EE_FK_AUTH_USER_ID)

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_SAVEDVIEW__DOCUMENTS_SAVEDVIEW_OWNER_ID_2DF222EE_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  private lateinit var _documentsSavedviewfilterrule: com.functionaldude.paperless.jooq.`public`.tables.DocumentsSavedviewfilterrule.DocumentsSavedviewfilterrulePath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_savedviewfilterrule</code> table
   */
  fun documentsSavedviewfilterrule(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsSavedviewfilterrule.DocumentsSavedviewfilterrulePath {
    if (!this::_documentsSavedviewfilterrule.isInitialized)
      _documentsSavedviewfilterrule =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsSavedviewfilterrule.DocumentsSavedviewfilterrulePath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_SAVEDVIEWFILTERRULE__DOCUMENTS_SAVEDVIEWF_SAVED_VIEW_ID_038E2C89_FK_DOCUMENTS.inverseKey
        )

    return _documentsSavedviewfilterrule;
  }

  val documentsSavedviewfilterrule: com.functionaldude.paperless.jooq.`public`.tables.DocumentsSavedviewfilterrule.DocumentsSavedviewfilterrulePath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsSavedviewfilterrule.DocumentsSavedviewfilterrulePath = documentsSavedviewfilterrule()

  override fun getChecks(): List<Check<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsSavedviewRecord>> =
    listOf(
      Internal.createCheck(this, DSL.name("documents_savedview_page_size_check"), "((page_size >= 0))", true)
    )

  override fun `as`(alias: String): DocumentsSavedview = DocumentsSavedview(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsSavedview = DocumentsSavedview(alias, this)
  override fun `as`(alias: Table<*>): DocumentsSavedview = DocumentsSavedview(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsSavedview = DocumentsSavedview(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsSavedview = DocumentsSavedview(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsSavedview = DocumentsSavedview(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsSavedview =
    DocumentsSavedview(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsSavedview = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsSavedview = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsSavedview = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsSavedview = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsSavedview = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsSavedview =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsSavedview =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsSavedview = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsSavedview = where(DSL.notExists(select))
}
