/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsPaperlesstask(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.documents_paperlesstask</code>
     */
    val DOCUMENTS_PAPERLESSTASK: DocumentsPaperlesstask = DocumentsPaperlesstask()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord::class.java

  /**
   * The column <code>public.documents_paperlesstask.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_paperlesstask.task_id</code>.
   */
  val TASK_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("task_id"), SQLDataType.VARCHAR(255).nullable(false), this, "")

  /**
   * The column <code>public.documents_paperlesstask.acknowledged</code>.
   */
  val ACKNOWLEDGED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, Boolean?> =
    createField(DSL.name("acknowledged"), SQLDataType.BOOLEAN.nullable(false), this, "")

  /**
   * The column <code>public.documents_paperlesstask.date_created</code>.
   */
  val DATE_CREATED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, OffsetDateTime?> =
    createField(DSL.name("date_created"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_paperlesstask.date_done</code>.
   */
  val DATE_DONE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, OffsetDateTime?> =
    createField(DSL.name("date_done"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_paperlesstask.date_started</code>.
   */
  val DATE_STARTED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, OffsetDateTime?> =
    createField(DSL.name("date_started"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  /**
   * The column <code>public.documents_paperlesstask.result</code>.
   */
  val RESULT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("result"), SQLDataType.CLOB, this, "")

  /**
   * The column <code>public.documents_paperlesstask.status</code>.
   */
  val STATUS: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("status"), SQLDataType.VARCHAR(30).nullable(false), this, "")

  /**
   * The column <code>public.documents_paperlesstask.task_name</code>.
   */
  val TASK_NAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("task_name"), SQLDataType.VARCHAR(255), this, "")

  /**
   * The column <code>public.documents_paperlesstask.task_file_name</code>.
   */
  val TASK_FILE_NAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("task_file_name"), SQLDataType.VARCHAR(255), this, "")

  /**
   * The column <code>public.documents_paperlesstask.owner_id</code>.
   */
  val OWNER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, Int?> =
    createField(DSL.name("owner_id"), SQLDataType.INTEGER, this, "")

  /**
   * The column <code>public.documents_paperlesstask.type</code>.
   */
  val TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, String?> =
    createField(DSL.name("type"), SQLDataType.VARCHAR(30).nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_paperlesstask</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_paperlesstask</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_paperlesstask</code> table reference
   */
  constructor() : this(DSL.name("documents_paperlesstask"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_PAPERLESSTASK,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsPaperlesstaskPath : DocumentsPaperlesstask,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsPaperlesstaskPath = DocumentsPaperlesstaskPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsPaperlesstaskPath = DocumentsPaperlesstaskPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsPaperlesstaskPath =
      DocumentsPaperlesstaskPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_PAPERLESSTASK_OWNER_ID_E4512F84,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_PAPERLESSTASK_TASK_ID_24B393F9_LIKE
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_PAPERLESSTASK_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_PAPERLESSTASK_TASK_ID_24B393F9_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsPaperlesstaskRecord, *>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_PAPERLESSTASK__DOCUMENTS_PAPERLESSTASK_OWNER_ID_E4512F84_FK_AUTH_USER_ID)

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_PAPERLESSTASK__DOCUMENTS_PAPERLESSTASK_OWNER_ID_E4512F84_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  override fun `as`(alias: String): DocumentsPaperlesstask = DocumentsPaperlesstask(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsPaperlesstask = DocumentsPaperlesstask(alias, this)
  override fun `as`(alias: Table<*>): DocumentsPaperlesstask = DocumentsPaperlesstask(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsPaperlesstask = DocumentsPaperlesstask(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsPaperlesstask = DocumentsPaperlesstask(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsPaperlesstask = DocumentsPaperlesstask(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsPaperlesstask =
    DocumentsPaperlesstask(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsPaperlesstask = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsPaperlesstask = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsPaperlesstask = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsPaperlesstask = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsPaperlesstask = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsPaperlesstask =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsPaperlesstask =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsPaperlesstask = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsPaperlesstask = where(DSL.notExists(select))
}
