/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowtriggerFilterHasNotCorrespondents(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) :
  TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>(
    alias,
    com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowtrigger_filter_has_not_correspondents</code>
     */
    val DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS: DocumentsWorkflowtriggerFilterHasNotCorrespondents =
      DocumentsWorkflowtriggerFilterHasNotCorrespondents()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord::class.java

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents.workflowtrigger_id</code>.
   */
  val WORKFLOWTRIGGER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, Int?> =
    createField(DSL.name("workflowtrigger_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents.correspondent_id</code>.
   */
  val CORRESPONDENT_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, Int?> =
    createField(DSL.name("correspondent_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents</code>
   * table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents</code>
   * table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a
   * <code>public.documents_workflowtrigger_filter_has_not_correspondents</code>
   * table reference
   */
  constructor() : this(DSL.name("documents_workflowtrigger_filter_has_not_correspondents"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath :
    DocumentsWorkflowtriggerFilterHasNotCorrespondents,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath =
      DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath =
      DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath(alias, this)

    override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath =
      DocumentsWorkflowtriggerFilterHasNotCorrespondentsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER__CORRESPONDENT_ID_AC4A7D73,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER__WORKFLOWTRIGGER_ID_BDF4F6CC
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGE_WORKFLOWTRIGGER_ID_CORRE_8EF9CD55_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS__DOCUMENTS_WORKFLOWTR_CORRESPONDENT_ID_AC4A7D73_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_BDF4F6CC_FK_DOCUMENTS
    )

  private lateinit var _documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_correspondent</code> table.
   */
  fun documentsCorrespondent(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath {
    if (!this::_documentsCorrespondent.isInitialized)
      _documentsCorrespondent =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS__DOCUMENTS_WORKFLOWTR_CORRESPONDENT_ID_AC4A7D73_FK_DOCUMENTS,
          null
        )

    return _documentsCorrespondent;
  }

  val documentsCorrespondent: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCorrespondent.DocumentsCorrespondentPath = documentsCorrespondent()

  private lateinit var _documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowtrigger</code> table.
   */
  fun documentsWorkflowtrigger(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath {
    if (!this::_documentsWorkflowtrigger.isInitialized)
      _documentsWorkflowtrigger =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_BDF4F6CC_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowtrigger;
  }

  val documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath = documentsWorkflowtrigger()

  override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(DSL.name(alias), this)

  override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(alias, this)

  override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    DocumentsWorkflowtriggerFilterHasNotCorrespondents(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg binds: Any?
  ): DocumentsWorkflowtriggerFilterHasNotCorrespondents = where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart
  ): DocumentsWorkflowtriggerFilterHasNotCorrespondents = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasNotCorrespondents =
    where(DSL.notExists(select))
}
