/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowactionRemoveViewGroups(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowaction_remove_view_groups</code>
     */
    val DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS: DocumentsWorkflowactionRemoveViewGroups =
      DocumentsWorkflowactionRemoveViewGroups()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord::class.java

  /**
   * The column
   * <code>public.documents_workflowaction_remove_view_groups.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction_remove_view_groups.workflowaction_id</code>.
   */
  val WORKFLOWACTION_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, Int?> =
    createField(DSL.name("workflowaction_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction_remove_view_groups.group_id</code>.
   */
  val GROUP_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, Int?> =
    createField(DSL.name("group_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased
   * <code>public.documents_workflowaction_remove_view_groups</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased
   * <code>public.documents_workflowaction_remove_view_groups</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_workflowaction_remove_view_groups</code>
   * table reference
   */
  constructor() : this(DSL.name("documents_workflowaction_remove_view_groups"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowactionRemoveViewGroupsPath : DocumentsWorkflowactionRemoveViewGroups,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowactionRemoveViewGroupsPath =
      DocumentsWorkflowactionRemoveViewGroupsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowactionRemoveViewGroupsPath =
      DocumentsWorkflowactionRemoveViewGroupsPath(alias, this)

    override fun `as`(alias: Table<*>): DocumentsWorkflowactionRemoveViewGroupsPath =
      DocumentsWorkflowactionRemoveViewGroupsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_R_WORKFLOWACTION_ID_8C532B6C,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS_GROUP_ID_43F07529
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_WORKFLOWACTION_ID_GROUP__84D7DE00_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionRemoveViewGroupsRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_GROUP_ID_43F07529_FK_AUTH_GROU,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_8C532B6C_FK_DOCUMENTS
    )

  private lateinit var _authGroup: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath

  /**
   * Get the implicit join path to the <code>public.auth_group</code> table.
   */
  fun authGroup(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath {
    if (!this::_authGroup.isInitialized)
      _authGroup = com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_GROUP_ID_43F07529_FK_AUTH_GROU,
        null
      )

    return _authGroup;
  }

  val authGroup: com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthGroup.AuthGroupPath = authGroup()

  private lateinit var _documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowaction</code> table.
   */
  fun documentsWorkflowaction(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath {
    if (!this::_documentsWorkflowaction.isInitialized)
      _documentsWorkflowaction =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_REMOVE_VIEW_GROUPS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_8C532B6C_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowaction;
  }

  val documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowaction()

  override fun `as`(alias: String): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(DSL.name(alias), this)

  override fun `as`(alias: Name): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(alias, this)

  override fun `as`(alias: Table<*>): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowactionRemoveViewGroups =
    DocumentsWorkflowactionRemoveViewGroups(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowactionRemoveViewGroups =
    where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowactionRemoveViewGroups =
    where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowactionRemoveViewGroups =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowactionRemoveViewGroups = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowactionRemoveViewGroups =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflowactionRemoveViewGroups =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart
  ): DocumentsWorkflowactionRemoveViewGroups = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowactionRemoveViewGroups = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowactionRemoveViewGroups = where(DSL.notExists(select))
}
