/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowtriggerFilterHasAnyStoragePaths(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) :
  TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>(
    alias,
    com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowtrigger_filter_has_any_storage_paths</code>
     */
    val DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS: DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
      DocumentsWorkflowtriggerFilterHasAnyStoragePaths()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord::class.java

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths.workflowtrigger_id</code>.
   */
  val WORKFLOWTRIGGER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, Int?> =
    createField(DSL.name("workflowtrigger_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths.storagepath_id</code>.
   */
  val STORAGEPATH_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, Int?> =
    createField(DSL.name("storagepath_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths</code>
   * table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths</code>
   * table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a
   * <code>public.documents_workflowtrigger_filter_has_any_storage_paths</code>
   * table reference
   */
  constructor() : this(DSL.name("documents_workflowtrigger_filter_has_any_storage_paths"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath : DocumentsWorkflowtriggerFilterHasAnyStoragePaths,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath =
      DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath =
      DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath(alias, this)

    override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath =
      DocumentsWorkflowtriggerFilterHasAnyStoragePathsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER__STORAGEPATH_ID_4F759B0D,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWTRIGGER__WORKFLOWTRIGGER_ID_5E9A227F
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGE_WORKFLOWTRIGGER_ID_STORA_DA181EDA_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowtriggerFilterHasAnyStoragePathsRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS__DOCUMENTS_WORKFLOWTR_STORAGEPATH_ID_4F759B0D_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_5E9A227F_FK_DOCUMENTS
    )

  private lateinit var _documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_storagepath</code> table.
   */
  fun documentsStoragepath(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath {
    if (!this::_documentsStoragepath.isInitialized)
      _documentsStoragepath =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS__DOCUMENTS_WORKFLOWTR_STORAGEPATH_ID_4F759B0D_FK_DOCUMENTS,
          null
        )

    return _documentsStoragepath;
  }

  val documentsStoragepath: com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DocumentsStoragepathPath = documentsStoragepath()

  private lateinit var _documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowtrigger</code> table.
   */
  fun documentsWorkflowtrigger(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath {
    if (!this::_documentsWorkflowtrigger.isInitialized)
      _documentsWorkflowtrigger =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_ANY_STORAGE_PATHS__DOCUMENTS_WORKFLOWTR_WORKFLOWTRIGGER_ID_5E9A227F_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowtrigger;
  }

  val documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath = documentsWorkflowtrigger()

  override fun `as`(alias: String): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(DSL.name(alias), this)

  override fun `as`(alias: Name): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(alias, this)

  override fun `as`(alias: Table<*>): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    DocumentsWorkflowtriggerFilterHasAnyStoragePaths(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowtriggerFilterHasAnyStoragePaths = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg binds: Any?
  ): DocumentsWorkflowtriggerFilterHasAnyStoragePaths = where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart
  ): DocumentsWorkflowtriggerFilterHasAnyStoragePaths = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowtriggerFilterHasAnyStoragePaths =
    where(DSL.notExists(select))
}
