/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowactionAssignCustomFields(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) :
  TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>(
    alias,
    com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
  ) {
  companion object {

    /**
     * The reference instance of
     * <code>public.documents_workflowaction_assign_custom_fields</code>
     */
    val DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS: DocumentsWorkflowactionAssignCustomFields =
      DocumentsWorkflowactionAssignCustomFields()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord::class.java

  /**
   * The column
   * <code>public.documents_workflowaction_assign_custom_fields.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction_assign_custom_fields.workflowaction_id</code>.
   */
  val WORKFLOWACTION_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, Int?> =
    createField(DSL.name("workflowaction_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column
   * <code>public.documents_workflowaction_assign_custom_fields.customfield_id</code>.
   */
  val CUSTOMFIELD_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, Int?> =
    createField(DSL.name("customfield_id"), SQLDataType.INTEGER.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased
   * <code>public.documents_workflowaction_assign_custom_fields</code> table
   * reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased
   * <code>public.documents_workflowaction_assign_custom_fields</code> table
   * reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a
   * <code>public.documents_workflowaction_assign_custom_fields</code> table
   * reference
   */
  constructor() : this(DSL.name("documents_workflowaction_assign_custom_fields"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowactionAssignCustomFieldsPath : DocumentsWorkflowactionAssignCustomFields,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowactionAssignCustomFieldsPath =
      DocumentsWorkflowactionAssignCustomFieldsPath(DSL.name(alias), this)

    override fun `as`(alias: Name): DocumentsWorkflowactionAssignCustomFieldsPath =
      DocumentsWorkflowactionAssignCustomFieldsPath(alias, this)

    override fun `as`(alias: Table<*>): DocumentsWorkflowactionAssignCustomFieldsPath =
      DocumentsWorkflowactionAssignCustomFieldsPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_A_CUSTOMFIELD_ID_09DF9CC4,
    com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOWACTION_A_WORKFLOWACTION_ID_518E70E5
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_WORKFLOWACTION_ID_CUSTOM_7325B36E_UNIQ)

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowactionAssignCustomFieldsRecord, *>> =
    listOf(
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_CUSTOMFIELD_ID_09DF9CC4_FK_DOCUMENTS,
      com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_518E70E5_FK_DOCUMENTS
    )

  private lateinit var _documentsCustomfield: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_customfield</code> table.
   */
  fun documentsCustomfield(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath {
    if (!this::_documentsCustomfield.isInitialized)
      _documentsCustomfield =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_CUSTOMFIELD_ID_09DF9CC4_FK_DOCUMENTS,
          null
        )

    return _documentsCustomfield;
  }

  val documentsCustomfield: com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsCustomfield.DocumentsCustomfieldPath = documentsCustomfield()

  private lateinit var _documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath

  /**
   * Get the implicit join path to the
   * <code>public.documents_workflowaction</code> table.
   */
  fun documentsWorkflowaction(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath {
    if (!this::_documentsWorkflowaction.isInitialized)
      _documentsWorkflowaction =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath(
          this,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWACTION_ASSIGN_CUSTOM_FIELDS__DOCUMENTS_WORKFLOWAC_WORKFLOWACTION_ID_518E70E5_FK_DOCUMENTS,
          null
        )

    return _documentsWorkflowaction;
  }

  val documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowaction()

  override fun `as`(alias: String): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(DSL.name(alias), this)

  override fun `as`(alias: Name): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(alias, this)

  override fun `as`(alias: Table<*>): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflowactionAssignCustomFields =
    DocumentsWorkflowactionAssignCustomFields(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflowactionAssignCustomFields = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(
    @Stringly.SQL condition: String,
    vararg parts: QueryPart
  ): DocumentsWorkflowactionAssignCustomFields = where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflowactionAssignCustomFields = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflowactionAssignCustomFields =
    where(DSL.notExists(select))
}
