/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import org.jooq.*
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflow(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.documents_workflow</code>
     */
    val DOCUMENTS_WORKFLOW: DocumentsWorkflow = DocumentsWorkflow()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord::class.java

  /**
   * The column <code>public.documents_workflow.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, Int?> =
    createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.documents_workflow.name</code>.
   */
  val NAME: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, String?> =
    createField(DSL.name("name"), SQLDataType.VARCHAR(256).nullable(false), this, "")

  /**
   * The column <code>public.documents_workflow.order</code>.
   */
  val ORDER: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, Int?> =
    createField(DSL.name("order"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column <code>public.documents_workflow.enabled</code>.
   */
  val ENABLED: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, Boolean?> =
    createField(DSL.name("enabled"), SQLDataType.BOOLEAN.nullable(false), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.documents_workflow</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.documents_workflow</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.documents_workflow</code> table reference
   */
  constructor() : this(DSL.name("documents_workflow"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    DOCUMENTS_WORKFLOW,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class DocumentsWorkflowPath : DocumentsWorkflow,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): DocumentsWorkflowPath = DocumentsWorkflowPath(DSL.name(alias), this)
    override fun `as`(alias: Name): DocumentsWorkflowPath = DocumentsWorkflowPath(alias, this)
    override fun `as`(alias: Table<*>): DocumentsWorkflowPath = DocumentsWorkflowPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> =
    listOf(com.functionaldude.paperless.jooq.`public`.indexes.DOCUMENTS_WORKFLOW_NAME_E88F7B19_LIKE)

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, Int?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord, Int?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOW_PKEY

  override fun getUniqueKeys(): List<UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.DocumentsWorkflowRecord>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOW_NAME_KEY)

  private lateinit var _documentsWorkflowActions: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflow_actions</code> table
   */
  fun documentsWorkflowActions(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath {
    if (!this::_documentsWorkflowActions.isInitialized)
      _documentsWorkflowActions =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOW_ACTIONS__DOCUMENTS_WORKFLOW_A_WORKFLOW_ID_5445F1DE_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowActions;
  }

  val documentsWorkflowActions: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DocumentsWorkflowActionsPath = documentsWorkflowActions()

  private lateinit var _documentsWorkflowTriggers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowTriggers.DocumentsWorkflowTriggersPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflow_triggers</code> table
   */
  fun documentsWorkflowTriggers(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowTriggers.DocumentsWorkflowTriggersPath {
    if (!this::_documentsWorkflowTriggers.isInitialized)
      _documentsWorkflowTriggers =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowTriggers.DocumentsWorkflowTriggersPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOW_TRIGGERS__DOCUMENTS_WORKFLOW_T_WORKFLOW_ID_77D63852_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowTriggers;
  }

  val documentsWorkflowTriggers: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowTriggers.DocumentsWorkflowTriggersPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowTriggers.DocumentsWorkflowTriggersPath = documentsWorkflowTriggers()

  private lateinit var _documentsWorkflowrun: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath

  /**
   * Get the implicit to-many join path to the
   * <code>public.documents_workflowrun</code> table
   */
  fun documentsWorkflowrun(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath {
    if (!this::_documentsWorkflowrun.isInitialized)
      _documentsWorkflowrun =
        com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath(
          this,
          null,
          com.functionaldude.paperless.jooq.`public`.keys.DOCUMENTS_WORKFLOWRUN__DOCUMENTS_WORKFLOWRU_WORKFLOW_ID_BEC88108_FK_DOCUMENTS.inverseKey
        )

    return _documentsWorkflowrun;
  }

  val documentsWorkflowrun: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowrun.DocumentsWorkflowrunPath = documentsWorkflowrun()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_workflowaction</code> table
   */
  val documentsWorkflowaction: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DocumentsWorkflowactionPath = documentsWorkflowActions().documentsWorkflowaction()

  /**
   * Get the implicit many-to-many join path to the
   * <code>public.documents_workflowtrigger</code> table
   */
  val documentsWorkflowtrigger: com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtrigger.DocumentsWorkflowtriggerPath = documentsWorkflowTriggers().documentsWorkflowtrigger()

  override fun `as`(alias: String): DocumentsWorkflow = DocumentsWorkflow(DSL.name(alias), this)
  override fun `as`(alias: Name): DocumentsWorkflow = DocumentsWorkflow(alias, this)
  override fun `as`(alias: Table<*>): DocumentsWorkflow = DocumentsWorkflow(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): DocumentsWorkflow = DocumentsWorkflow(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): DocumentsWorkflow = DocumentsWorkflow(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): DocumentsWorkflow = DocumentsWorkflow(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): DocumentsWorkflow =
    DocumentsWorkflow(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): DocumentsWorkflow = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): DocumentsWorkflow = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): DocumentsWorkflow = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): DocumentsWorkflow = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): DocumentsWorkflow = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): DocumentsWorkflow =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): DocumentsWorkflow =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): DocumentsWorkflow = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): DocumentsWorkflow = where(DSL.notExists(select))
}
