/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables


import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class MfaAuthenticator(
  alias: Name,
  path: Table<out Record>?,
  childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
  parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
  aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
  parameters: Array<Field<*>?>?,
  where: Condition?
) : TableImpl<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>(
  alias,
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table(),
  where,
) {
  companion object {

    /**
     * The reference instance of <code>public.mfa_authenticator</code>
     */
    val MFA_AUTHENTICATOR: MfaAuthenticator = MfaAuthenticator()
  }

  /**
   * The class holding records for this type
   */
  override fun getRecordType(): Class<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord> =
    com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord::class.java

  /**
   * The column <code>public.mfa_authenticator.id</code>.
   */
  val ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, Long?> =
    createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

  /**
   * The column <code>public.mfa_authenticator.type</code>.
   */
  val TYPE: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, String?> =
    createField(DSL.name("type"), SQLDataType.VARCHAR(20).nullable(false), this, "")

  /**
   * The column <code>public.mfa_authenticator.data</code>.
   */
  val DATA: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, JSONB?> =
    createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "")

  /**
   * The column <code>public.mfa_authenticator.user_id</code>.
   */
  val USER_ID: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, Int?> =
    createField(DSL.name("user_id"), SQLDataType.INTEGER.nullable(false), this, "")

  /**
   * The column <code>public.mfa_authenticator.created_at</code>.
   */
  val CREATED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, OffsetDateTime?> =
    createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

  /**
   * The column <code>public.mfa_authenticator.last_used_at</code>.
   */
  val LAST_USED_AT: TableField<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, OffsetDateTime?> =
    createField(DSL.name("last_used_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "")

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?
  ) : this(alias, null, null, null, aliased, null, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
    parameters: Array<Field<*>?>?
  ) : this(alias, null, null, null, aliased, parameters, null)

  private constructor(
    alias: Name,
    aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
    where: Condition?
  ) : this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.mfa_authenticator</code> table reference
   */
  constructor(alias: String) : this(DSL.name(alias))

  /**
   * Create an aliased <code>public.mfa_authenticator</code> table reference
   */
  constructor(alias: Name) : this(alias, null)

  /**
   * Create a <code>public.mfa_authenticator</code> table reference
   */
  constructor() : this(DSL.name("mfa_authenticator"), null)

  constructor(
    path: Table<out Record>,
    childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
    parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?
  ) : this(
    Internal.createPathAlias(path, childPath, parentPath),
    path,
    childPath,
    parentPath,
    MFA_AUTHENTICATOR,
    null,
    null
  )

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  open class MfaAuthenticatorPath : MfaAuthenticator,
    Path<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord> {
    constructor(
      path: Table<out Record>,
      childPath: ForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?,
      parentPath: InverseForeignKey<out Record, com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>?
    ) : super(path, childPath, parentPath)

    private constructor(
      alias: Name,
      aliased: Table<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord>
    ) : super(alias, aliased)

    override fun `as`(alias: String): MfaAuthenticatorPath = MfaAuthenticatorPath(DSL.name(alias), this)
    override fun `as`(alias: Name): MfaAuthenticatorPath = MfaAuthenticatorPath(alias, this)
    override fun `as`(alias: Table<*>): MfaAuthenticatorPath = MfaAuthenticatorPath(alias.qualifiedName, this)
  }

  override fun getSchema(): Schema? = if (aliased()) null else com.functionaldude.paperless.jooq.`public`.Public.PUBLIC
  override fun getIndexes(): List<Index> = listOf(
    com.functionaldude.paperless.jooq.`public`.indexes.MFA_AUTHENTICATOR_USER_ID_0C3A50C0,
    com.functionaldude.paperless.jooq.`public`.indexes.UNIQUE_AUTHENTICATOR_TYPE
  )

  override fun getIdentity(): Identity<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, Long?> =
    super.getIdentity() as Identity<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, Long?>

  override fun getPrimaryKey(): UniqueKey<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord> =
    com.functionaldude.paperless.jooq.`public`.keys.MFA_AUTHENTICATOR_PKEY

  override fun getReferences(): List<ForeignKey<com.functionaldude.paperless.jooq.`public`.tables.records.MfaAuthenticatorRecord, *>> =
    listOf(com.functionaldude.paperless.jooq.`public`.keys.MFA_AUTHENTICATOR__MFA_AUTHENTICATOR_USER_ID_0C3A50C0_FK_AUTH_USER_ID)

  private lateinit var _authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath

  /**
   * Get the implicit join path to the <code>public.auth_user</code> table.
   */
  fun authUser(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath {
    if (!this::_authUser.isInitialized)
      _authUser = com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath(
        this,
        com.functionaldude.paperless.jooq.`public`.keys.MFA_AUTHENTICATOR__MFA_AUTHENTICATOR_USER_ID_0C3A50C0_FK_AUTH_USER_ID,
        null
      )

    return _authUser;
  }

  val authUser: com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath
    get(): com.functionaldude.paperless.jooq.`public`.tables.AuthUser.AuthUserPath = authUser()

  override fun `as`(alias: String): MfaAuthenticator = MfaAuthenticator(DSL.name(alias), this)
  override fun `as`(alias: Name): MfaAuthenticator = MfaAuthenticator(alias, this)
  override fun `as`(alias: Table<*>): MfaAuthenticator = MfaAuthenticator(alias.qualifiedName, this)

  /**
   * Rename this table
   */
  override fun rename(name: String): MfaAuthenticator = MfaAuthenticator(DSL.name(name), null)

  /**
   * Rename this table
   */
  override fun rename(name: Name): MfaAuthenticator = MfaAuthenticator(name, null)

  /**
   * Rename this table
   */
  override fun rename(name: Table<*>): MfaAuthenticator = MfaAuthenticator(name.qualifiedName, null)

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Condition?): MfaAuthenticator =
    MfaAuthenticator(qualifiedName, if (aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override fun where(conditions: Collection<Condition>): MfaAuthenticator = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(vararg conditions: Condition?): MfaAuthenticator = where(DSL.and(*conditions))

  /**
   * Create an inline derived table from this table
   */
  override fun where(condition: Field<Boolean?>?): MfaAuthenticator = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(condition: SQL): MfaAuthenticator = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String): MfaAuthenticator = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg binds: Any?): MfaAuthenticator =
    where(DSL.condition(condition, *binds))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL
  override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): MfaAuthenticator =
    where(DSL.condition(condition, *parts))

  /**
   * Create an inline derived table from this table
   */
  override fun whereExists(select: Select<*>): MfaAuthenticator = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override fun whereNotExists(select: Select<*>): MfaAuthenticator = where(DSL.notExists(select))
}
