/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AccountEmailaddressRecord() :
  UpdatableRecordImpl<AccountEmailaddressRecord>(com.functionaldude.paperless.jooq.`public`.tables.AccountEmailaddress.ACCOUNT_EMAILADDRESS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var email: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var verified: Boolean?
    set(value): Unit = set(2, value)
    get(): Boolean? = get(2) as Boolean?

  open var primary: Boolean?
    set(value): Unit = set(3, value)
    get(): Boolean? = get(3) as Boolean?

  open var userId: Int?
    set(value): Unit = set(4, value)
    get(): Int? = get(4) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised AccountEmailaddressRecord
   */
  constructor(
    id: Int? = null,
    email: String? = null,
    verified: Boolean? = null,
    primary: Boolean? = null,
    userId: Int? = null
  ) : this() {
    this.id = id
    this.email = email
    this.verified = verified
    this.primary = primary
    this.userId = userId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised AccountEmailaddressRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.AccountEmailaddress?) : this() {
    if (value != null) {
      this.id = value.id
      this.email = value.email
      this.verified = value.verified
      this.primary = value.primary
      this.userId = value.userId
      resetChangedOnNotNull()
    }
  }
}
