/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthtokenTokenRecord() :
  UpdatableRecordImpl<AuthtokenTokenRecord>(com.functionaldude.paperless.jooq.`public`.tables.AuthtokenToken.AUTHTOKEN_TOKEN) {

  open var key: String?
    set(value): Unit = set(0, value)
    get(): String? = get(0) as String?

  open var created: OffsetDateTime?
    set(value): Unit = set(1, value)
    get(): OffsetDateTime? = get(1) as OffsetDateTime?

  open var userId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<String?> = super.key() as Record1<String?>

  /**
   * Create a detached, initialised AuthtokenTokenRecord
   */
  constructor(key: String? = null, created: OffsetDateTime? = null, userId: Int? = null) : this() {
    this.key = key
    this.created = created
    this.userId = userId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised AuthtokenTokenRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.AuthtokenToken?) : this() {
    if (value != null) {
      this.key = value.key
      this.created = value.created
      this.userId = value.userId
      resetChangedOnNotNull()
    }
  }
}
