/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthUserUserPermissionsRecord() :
  UpdatableRecordImpl<AuthUserUserPermissionsRecord>(com.functionaldude.paperless.jooq.`public`.tables.AuthUserUserPermissions.AUTH_USER_USER_PERMISSIONS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var userId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var permissionId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised AuthUserUserPermissionsRecord
   */
  constructor(id: Int? = null, userId: Int? = null, permissionId: Int? = null) : this() {
    this.id = id
    this.userId = userId
    this.permissionId = permissionId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised AuthUserUserPermissionsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.AuthUserUserPermissions?) : this() {
    if (value != null) {
      this.id = value.id
      this.userId = value.userId
      this.permissionId = value.permissionId
      resetChangedOnNotNull()
    }
  }
}
