/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class AuthUserGroupsRecord() :
  UpdatableRecordImpl<AuthUserGroupsRecord>(com.functionaldude.paperless.jooq.`public`.tables.AuthUserGroups.AUTH_USER_GROUPS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var userId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var groupId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised AuthUserGroupsRecord
   */
  constructor(id: Int? = null, userId: Int? = null, groupId: Int? = null) : this() {
    this.id = id
    this.userId = userId
    this.groupId = groupId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised AuthUserGroupsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.AuthUserGroups?) : this() {
    if (value != null) {
      this.id = value.id
      this.userId = value.userId
      this.groupId = value.groupId
      resetChangedOnNotNull()
    }
  }
}
