/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoAdminLogRecord() :
  UpdatableRecordImpl<DjangoAdminLogRecord>(com.functionaldude.paperless.jooq.`public`.tables.DjangoAdminLog.DJANGO_ADMIN_LOG) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var actionTime: OffsetDateTime?
    set(value): Unit = set(1, value)
    get(): OffsetDateTime? = get(1) as OffsetDateTime?

  open var objectId: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var objectRepr: String?
    set(value): Unit = set(3, value)
    get(): String? = get(3) as String?

  open var actionFlag: Short?
    set(value): Unit = set(4, value)
    get(): Short? = get(4) as Short?

  open var changeMessage: String?
    set(value): Unit = set(5, value)
    get(): String? = get(5) as String?

  open var contentTypeId: Int?
    set(value): Unit = set(6, value)
    get(): Int? = get(6) as Int?

  open var userId: Int?
    set(value): Unit = set(7, value)
    get(): Int? = get(7) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DjangoAdminLogRecord
   */
  constructor(
    id: Int? = null,
    actionTime: OffsetDateTime? = null,
    objectId: String? = null,
    objectRepr: String? = null,
    actionFlag: Short? = null,
    changeMessage: String? = null,
    contentTypeId: Int? = null,
    userId: Int? = null
  ) : this() {
    this.id = id
    this.actionTime = actionTime
    this.objectId = objectId
    this.objectRepr = objectRepr
    this.actionFlag = actionFlag
    this.changeMessage = changeMessage
    this.contentTypeId = contentTypeId
    this.userId = userId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DjangoAdminLogRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DjangoAdminLog?) : this() {
    if (value != null) {
      this.id = value.id
      this.actionTime = value.actionTime
      this.objectId = value.objectId
      this.objectRepr = value.objectRepr
      this.actionFlag = value.actionFlag
      this.changeMessage = value.changeMessage
      this.contentTypeId = value.contentTypeId
      this.userId = value.userId
      resetChangedOnNotNull()
    }
  }
}
