/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoCeleryResultsTaskresultRecord() :
  UpdatableRecordImpl<DjangoCeleryResultsTaskresultRecord>(com.functionaldude.paperless.jooq.`public`.tables.DjangoCeleryResultsTaskresult.DJANGO_CELERY_RESULTS_TASKRESULT) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var taskId: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var status: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var contentType: String?
    set(value): Unit = set(3, value)
    get(): String? = get(3) as String?

  open var contentEncoding: String?
    set(value): Unit = set(4, value)
    get(): String? = get(4) as String?

  open var result: String?
    set(value): Unit = set(5, value)
    get(): String? = get(5) as String?

  open var dateDone: OffsetDateTime?
    set(value): Unit = set(6, value)
    get(): OffsetDateTime? = get(6) as OffsetDateTime?

  open var traceback: String?
    set(value): Unit = set(7, value)
    get(): String? = get(7) as String?

  open var meta: String?
    set(value): Unit = set(8, value)
    get(): String? = get(8) as String?

  open var taskArgs: String?
    set(value): Unit = set(9, value)
    get(): String? = get(9) as String?

  open var taskKwargs: String?
    set(value): Unit = set(10, value)
    get(): String? = get(10) as String?

  open var taskName: String?
    set(value): Unit = set(11, value)
    get(): String? = get(11) as String?

  open var worker: String?
    set(value): Unit = set(12, value)
    get(): String? = get(12) as String?

  open var dateCreated: OffsetDateTime?
    set(value): Unit = set(13, value)
    get(): OffsetDateTime? = get(13) as OffsetDateTime?

  open var periodicTaskName: String?
    set(value): Unit = set(14, value)
    get(): String? = get(14) as String?

  open var dateStarted: OffsetDateTime?
    set(value): Unit = set(15, value)
    get(): OffsetDateTime? = get(15) as OffsetDateTime?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DjangoCeleryResultsTaskresultRecord
   */
  constructor(
    id: Int? = null,
    taskId: String? = null,
    status: String? = null,
    contentType: String? = null,
    contentEncoding: String? = null,
    result: String? = null,
    dateDone: OffsetDateTime? = null,
    traceback: String? = null,
    meta: String? = null,
    taskArgs: String? = null,
    taskKwargs: String? = null,
    taskName: String? = null,
    worker: String? = null,
    dateCreated: OffsetDateTime? = null,
    periodicTaskName: String? = null,
    dateStarted: OffsetDateTime? = null
  ) : this() {
    this.id = id
    this.taskId = taskId
    this.status = status
    this.contentType = contentType
    this.contentEncoding = contentEncoding
    this.result = result
    this.dateDone = dateDone
    this.traceback = traceback
    this.meta = meta
    this.taskArgs = taskArgs
    this.taskKwargs = taskKwargs
    this.taskName = taskName
    this.worker = worker
    this.dateCreated = dateCreated
    this.periodicTaskName = periodicTaskName
    this.dateStarted = dateStarted
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DjangoCeleryResultsTaskresultRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DjangoCeleryResultsTaskresult?) : this() {
    if (value != null) {
      this.id = value.id
      this.taskId = value.taskId
      this.status = value.status
      this.contentType = value.contentType
      this.contentEncoding = value.contentEncoding
      this.result = value.result
      this.dateDone = value.dateDone
      this.traceback = value.traceback
      this.meta = value.meta
      this.taskArgs = value.taskArgs
      this.taskKwargs = value.taskKwargs
      this.taskName = value.taskName
      this.worker = value.worker
      this.dateCreated = value.dateCreated
      this.periodicTaskName = value.periodicTaskName
      this.dateStarted = value.dateStarted
      resetChangedOnNotNull()
    }
  }
}
