/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DjangoCeleryResultsChordcounterRecord() :
  UpdatableRecordImpl<DjangoCeleryResultsChordcounterRecord>(com.functionaldude.paperless.jooq.`public`.tables.DjangoCeleryResultsChordcounter.DJANGO_CELERY_RESULTS_CHORDCOUNTER) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var groupId: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var subTasks: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var count: Int?
    set(value): Unit = set(3, value)
    get(): Int? = get(3) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DjangoCeleryResultsChordcounterRecord
   */
  constructor(id: Int? = null, groupId: String? = null, subTasks: String? = null, count: Int? = null) : this() {
    this.id = id
    this.groupId = groupId
    this.subTasks = subTasks
    this.count = count
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DjangoCeleryResultsChordcounterRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DjangoCeleryResultsChordcounter?) : this() {
    if (value != null) {
      this.id = value.id
      this.groupId = value.groupId
      this.subTasks = value.subTasks
      this.count = value.count
      resetChangedOnNotNull()
    }
  }
}
