/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsTagRecord() :
  UpdatableRecordImpl<DocumentsTagRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsTag.DOCUMENTS_TAG) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var name: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var match: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var matchingAlgorithm: Int?
    set(value): Unit = set(3, value)
    get(): Int? = get(3) as Int?

  @Suppress("INAPPLICABLE_JVM_NAME")
  @set:JvmName("setIsInsensitive")
  open var isInsensitive: Boolean?
    set(value): Unit = set(4, value)
    get(): Boolean? = get(4) as Boolean?

  @Suppress("INAPPLICABLE_JVM_NAME")
  @set:JvmName("setIsInboxTag")
  open var isInboxTag: Boolean?
    set(value): Unit = set(5, value)
    get(): Boolean? = get(5) as Boolean?

  open var color: String?
    set(value): Unit = set(6, value)
    get(): String? = get(6) as String?

  open var ownerId: Int?
    set(value): Unit = set(7, value)
    get(): Int? = get(7) as Int?

  open var tnAncestorsCount: Int?
    set(value): Unit = set(8, value)
    get(): Int? = get(8) as Int?

  open var tnAncestorsPks: String?
    set(value): Unit = set(9, value)
    get(): String? = get(9) as String?

  open var tnChildrenCount: Int?
    set(value): Unit = set(10, value)
    get(): Int? = get(10) as Int?

  open var tnChildrenPks: String?
    set(value): Unit = set(11, value)
    get(): String? = get(11) as String?

  open var tnDepth: Int?
    set(value): Unit = set(12, value)
    get(): Int? = get(12) as Int?

  open var tnDescendantsCount: Int?
    set(value): Unit = set(13, value)
    get(): Int? = get(13) as Int?

  open var tnDescendantsPks: String?
    set(value): Unit = set(14, value)
    get(): String? = get(14) as String?

  open var tnIndex: Int?
    set(value): Unit = set(15, value)
    get(): Int? = get(15) as Int?

  open var tnLevel: Int?
    set(value): Unit = set(16, value)
    get(): Int? = get(16) as Int?

  open var tnOrder: Int?
    set(value): Unit = set(17, value)
    get(): Int? = get(17) as Int?

  open var tnParentId: Int?
    set(value): Unit = set(18, value)
    get(): Int? = get(18) as Int?

  open var tnPriority: Int?
    set(value): Unit = set(19, value)
    get(): Int? = get(19) as Int?

  open var tnSiblingsCount: Int?
    set(value): Unit = set(20, value)
    get(): Int? = get(20) as Int?

  open var tnSiblingsPks: String?
    set(value): Unit = set(21, value)
    get(): String? = get(21) as String?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsTagRecord
   */
  constructor(
    id: Int? = null,
    name: String? = null,
    match: String? = null,
    matchingAlgorithm: Int? = null,
    isInsensitive: Boolean? = null,
    isInboxTag: Boolean? = null,
    color: String? = null,
    ownerId: Int? = null,
    tnAncestorsCount: Int? = null,
    tnAncestorsPks: String? = null,
    tnChildrenCount: Int? = null,
    tnChildrenPks: String? = null,
    tnDepth: Int? = null,
    tnDescendantsCount: Int? = null,
    tnDescendantsPks: String? = null,
    tnIndex: Int? = null,
    tnLevel: Int? = null,
    tnOrder: Int? = null,
    tnParentId: Int? = null,
    tnPriority: Int? = null,
    tnSiblingsCount: Int? = null,
    tnSiblingsPks: String? = null
  ) : this() {
    this.id = id
    this.name = name
    this.match = match
    this.matchingAlgorithm = matchingAlgorithm
    this.isInsensitive = isInsensitive
    this.isInboxTag = isInboxTag
    this.color = color
    this.ownerId = ownerId
    this.tnAncestorsCount = tnAncestorsCount
    this.tnAncestorsPks = tnAncestorsPks
    this.tnChildrenCount = tnChildrenCount
    this.tnChildrenPks = tnChildrenPks
    this.tnDepth = tnDepth
    this.tnDescendantsCount = tnDescendantsCount
    this.tnDescendantsPks = tnDescendantsPks
    this.tnIndex = tnIndex
    this.tnLevel = tnLevel
    this.tnOrder = tnOrder
    this.tnParentId = tnParentId
    this.tnPriority = tnPriority
    this.tnSiblingsCount = tnSiblingsCount
    this.tnSiblingsPks = tnSiblingsPks
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsTagRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsTag?) : this() {
    if (value != null) {
      this.id = value.id
      this.name = value.name
      this.match = value.match
      this.matchingAlgorithm = value.matchingAlgorithm
      this.isInsensitive = value.isInsensitive
      this.isInboxTag = value.isInboxTag
      this.color = value.color
      this.ownerId = value.ownerId
      this.tnAncestorsCount = value.tnAncestorsCount
      this.tnAncestorsPks = value.tnAncestorsPks
      this.tnChildrenCount = value.tnChildrenCount
      this.tnChildrenPks = value.tnChildrenPks
      this.tnDepth = value.tnDepth
      this.tnDescendantsCount = value.tnDescendantsCount
      this.tnDescendantsPks = value.tnDescendantsPks
      this.tnIndex = value.tnIndex
      this.tnLevel = value.tnLevel
      this.tnOrder = value.tnOrder
      this.tnParentId = value.tnParentId
      this.tnPriority = value.tnPriority
      this.tnSiblingsCount = value.tnSiblingsCount
      this.tnSiblingsPks = value.tnSiblingsPks
      resetChangedOnNotNull()
    }
  }
}
