/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowactionRecord() :
  UpdatableRecordImpl<DocumentsWorkflowactionRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowaction.DOCUMENTS_WORKFLOWACTION) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var type: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var assignTitle: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var assignCorrespondentId: Int?
    set(value): Unit = set(3, value)
    get(): Int? = get(3) as Int?

  open var assignDocumentTypeId: Int?
    set(value): Unit = set(4, value)
    get(): Int? = get(4) as Int?

  open var assignOwnerId: Int?
    set(value): Unit = set(5, value)
    get(): Int? = get(5) as Int?

  open var assignStoragePathId: Int?
    set(value): Unit = set(6, value)
    get(): Int? = get(6) as Int?

  open var removeAllCorrespondents: Boolean?
    set(value): Unit = set(7, value)
    get(): Boolean? = get(7) as Boolean?

  open var removeAllCustomFields: Boolean?
    set(value): Unit = set(8, value)
    get(): Boolean? = get(8) as Boolean?

  open var removeAllDocumentTypes: Boolean?
    set(value): Unit = set(9, value)
    get(): Boolean? = get(9) as Boolean?

  open var removeAllOwners: Boolean?
    set(value): Unit = set(10, value)
    get(): Boolean? = get(10) as Boolean?

  open var removeAllPermissions: Boolean?
    set(value): Unit = set(11, value)
    get(): Boolean? = get(11) as Boolean?

  open var removeAllStoragePaths: Boolean?
    set(value): Unit = set(12, value)
    get(): Boolean? = get(12) as Boolean?

  open var removeAllTags: Boolean?
    set(value): Unit = set(13, value)
    get(): Boolean? = get(13) as Boolean?

  open var emailId: Int?
    set(value): Unit = set(14, value)
    get(): Int? = get(14) as Int?

  open var webhookId: Int?
    set(value): Unit = set(15, value)
    get(): Int? = get(15) as Int?

  open var assignCustomFieldsValues: JSONB?
    set(value): Unit = set(16, value)
    get(): JSONB? = get(16) as JSONB?

  open var order: Int?
    set(value): Unit = set(17, value)
    get(): Int? = get(17) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsWorkflowactionRecord
   */
  constructor(
    id: Int? = null,
    type: Int? = null,
    assignTitle: String? = null,
    assignCorrespondentId: Int? = null,
    assignDocumentTypeId: Int? = null,
    assignOwnerId: Int? = null,
    assignStoragePathId: Int? = null,
    removeAllCorrespondents: Boolean? = null,
    removeAllCustomFields: Boolean? = null,
    removeAllDocumentTypes: Boolean? = null,
    removeAllOwners: Boolean? = null,
    removeAllPermissions: Boolean? = null,
    removeAllStoragePaths: Boolean? = null,
    removeAllTags: Boolean? = null,
    emailId: Int? = null,
    webhookId: Int? = null,
    assignCustomFieldsValues: JSONB? = null,
    order: Int? = null
  ) : this() {
    this.id = id
    this.type = type
    this.assignTitle = assignTitle
    this.assignCorrespondentId = assignCorrespondentId
    this.assignDocumentTypeId = assignDocumentTypeId
    this.assignOwnerId = assignOwnerId
    this.assignStoragePathId = assignStoragePathId
    this.removeAllCorrespondents = removeAllCorrespondents
    this.removeAllCustomFields = removeAllCustomFields
    this.removeAllDocumentTypes = removeAllDocumentTypes
    this.removeAllOwners = removeAllOwners
    this.removeAllPermissions = removeAllPermissions
    this.removeAllStoragePaths = removeAllStoragePaths
    this.removeAllTags = removeAllTags
    this.emailId = emailId
    this.webhookId = webhookId
    this.assignCustomFieldsValues = assignCustomFieldsValues
    this.order = order
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsWorkflowactionRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsWorkflowaction?) : this() {
    if (value != null) {
      this.id = value.id
      this.type = value.type
      this.assignTitle = value.assignTitle
      this.assignCorrespondentId = value.assignCorrespondentId
      this.assignDocumentTypeId = value.assignDocumentTypeId
      this.assignOwnerId = value.assignOwnerId
      this.assignStoragePathId = value.assignStoragePathId
      this.removeAllCorrespondents = value.removeAllCorrespondents
      this.removeAllCustomFields = value.removeAllCustomFields
      this.removeAllDocumentTypes = value.removeAllDocumentTypes
      this.removeAllOwners = value.removeAllOwners
      this.removeAllPermissions = value.removeAllPermissions
      this.removeAllStoragePaths = value.removeAllStoragePaths
      this.removeAllTags = value.removeAllTags
      this.emailId = value.emailId
      this.webhookId = value.webhookId
      this.assignCustomFieldsValues = value.assignCustomFieldsValues
      this.order = value.order
      resetChangedOnNotNull()
    }
  }
}
