/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord() :
  UpdatableRecordImpl<DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowtriggerFilterHasNotCorrespondents.DOCUMENTS_WORKFLOWTRIGGER_FILTER_HAS_NOT_CORRESPONDENTS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var workflowtriggerId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var correspondentId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised
   * DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord
   */
  constructor(id: Int? = null, workflowtriggerId: Int? = null, correspondentId: Int? = null) : this() {
    this.id = id
    this.workflowtriggerId = workflowtriggerId
    this.correspondentId = correspondentId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised
   * DocumentsWorkflowtriggerFilterHasNotCorrespondentsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsWorkflowtriggerFilterHasNotCorrespondents?) : this() {
    if (value != null) {
      this.id = value.id
      this.workflowtriggerId = value.workflowtriggerId
      this.correspondentId = value.correspondentId
      resetChangedOnNotNull()
    }
  }
}
