/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowactionRemoveTagsRecord() :
  UpdatableRecordImpl<DocumentsWorkflowactionRemoveTagsRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowactionRemoveTags.DOCUMENTS_WORKFLOWACTION_REMOVE_TAGS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var workflowactionId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var tagId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsWorkflowactionRemoveTagsRecord
   */
  constructor(id: Int? = null, workflowactionId: Int? = null, tagId: Int? = null) : this() {
    this.id = id
    this.workflowactionId = workflowactionId
    this.tagId = tagId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsWorkflowactionRemoveTagsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsWorkflowactionRemoveTags?) : this() {
    if (value != null) {
      this.id = value.id
      this.workflowactionId = value.workflowactionId
      this.tagId = value.tagId
      resetChangedOnNotNull()
    }
  }
}
