/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsWorkflowActionsRecord() :
  UpdatableRecordImpl<DocumentsWorkflowActionsRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsWorkflowActions.DOCUMENTS_WORKFLOW_ACTIONS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var workflowId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var workflowactionId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsWorkflowActionsRecord
   */
  constructor(id: Int? = null, workflowId: Int? = null, workflowactionId: Int? = null) : this() {
    this.id = id
    this.workflowId = workflowId
    this.workflowactionId = workflowactionId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsWorkflowActionsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsWorkflowActions?) : this() {
    if (value != null) {
      this.id = value.id
      this.workflowId = value.workflowId
      this.workflowactionId = value.workflowactionId
      resetChangedOnNotNull()
    }
  }
}
