/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsStoragepathRecord() :
  UpdatableRecordImpl<DocumentsStoragepathRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsStoragepath.DOCUMENTS_STORAGEPATH) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var name: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var match: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var matchingAlgorithm: Int?
    set(value): Unit = set(3, value)
    get(): Int? = get(3) as Int?

  @Suppress("INAPPLICABLE_JVM_NAME")
  @set:JvmName("setIsInsensitive")
  open var isInsensitive: Boolean?
    set(value): Unit = set(4, value)
    get(): Boolean? = get(4) as Boolean?

  open var path: String?
    set(value): Unit = set(5, value)
    get(): String? = get(5) as String?

  open var ownerId: Int?
    set(value): Unit = set(6, value)
    get(): Int? = get(6) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsStoragepathRecord
   */
  constructor(
    id: Int? = null,
    name: String? = null,
    match: String? = null,
    matchingAlgorithm: Int? = null,
    isInsensitive: Boolean? = null,
    path: String? = null,
    ownerId: Int? = null
  ) : this() {
    this.id = id
    this.name = name
    this.match = match
    this.matchingAlgorithm = matchingAlgorithm
    this.isInsensitive = isInsensitive
    this.path = path
    this.ownerId = ownerId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsStoragepathRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsStoragepath?) : this() {
    if (value != null) {
      this.id = value.id
      this.name = value.name
      this.match = value.match
      this.matchingAlgorithm = value.matchingAlgorithm
      this.isInsensitive = value.isInsensitive
      this.path = value.path
      this.ownerId = value.ownerId
      resetChangedOnNotNull()
    }
  }
}
