/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime
import java.util.*


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class DocumentsSharelinkRecord() :
  UpdatableRecordImpl<DocumentsSharelinkRecord>(com.functionaldude.paperless.jooq.`public`.tables.DocumentsSharelink.DOCUMENTS_SHARELINK) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var created: OffsetDateTime?
    set(value): Unit = set(1, value)
    get(): OffsetDateTime? = get(1) as OffsetDateTime?

  open var expiration: OffsetDateTime?
    set(value): Unit = set(2, value)
    get(): OffsetDateTime? = get(2) as OffsetDateTime?

  open var slug: String?
    set(value): Unit = set(3, value)
    get(): String? = get(3) as String?

  open var fileVersion: String?
    set(value): Unit = set(4, value)
    get(): String? = get(4) as String?

  open var documentId: Int?
    set(value): Unit = set(5, value)
    get(): Int? = get(5) as Int?

  open var ownerId: Int?
    set(value): Unit = set(6, value)
    get(): Int? = get(6) as Int?

  open var deletedAt: OffsetDateTime?
    set(value): Unit = set(7, value)
    get(): OffsetDateTime? = get(7) as OffsetDateTime?

  open var restoredAt: OffsetDateTime?
    set(value): Unit = set(8, value)
    get(): OffsetDateTime? = get(8) as OffsetDateTime?

  open var transactionId: UUID?
    set(value): Unit = set(9, value)
    get(): UUID? = get(9) as UUID?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised DocumentsSharelinkRecord
   */
  constructor(
    id: Int? = null,
    created: OffsetDateTime? = null,
    expiration: OffsetDateTime? = null,
    slug: String? = null,
    fileVersion: String? = null,
    documentId: Int? = null,
    ownerId: Int? = null,
    deletedAt: OffsetDateTime? = null,
    restoredAt: OffsetDateTime? = null,
    transactionId: UUID? = null
  ) : this() {
    this.id = id
    this.created = created
    this.expiration = expiration
    this.slug = slug
    this.fileVersion = fileVersion
    this.documentId = documentId
    this.ownerId = ownerId
    this.deletedAt = deletedAt
    this.restoredAt = restoredAt
    this.transactionId = transactionId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised DocumentsSharelinkRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.DocumentsSharelink?) : this() {
    if (value != null) {
      this.id = value.id
      this.created = value.created
      this.expiration = value.expiration
      this.slug = value.slug
      this.fileVersion = value.fileVersion
      this.documentId = value.documentId
      this.ownerId = value.ownerId
      this.deletedAt = value.deletedAt
      this.restoredAt = value.restoredAt
      this.transactionId = value.transactionId
      resetChangedOnNotNull()
    }
  }
}
