/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class GuardianGroupobjectpermissionRecord() :
  UpdatableRecordImpl<GuardianGroupobjectpermissionRecord>(com.functionaldude.paperless.jooq.`public`.tables.GuardianGroupobjectpermission.GUARDIAN_GROUPOBJECTPERMISSION) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var objectPk: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var contentTypeId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  open var groupId: Int?
    set(value): Unit = set(3, value)
    get(): Int? = get(3) as Int?

  open var permissionId: Int?
    set(value): Unit = set(4, value)
    get(): Int? = get(4) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised GuardianGroupobjectpermissionRecord
   */
  constructor(
    id: Int? = null,
    objectPk: String? = null,
    contentTypeId: Int? = null,
    groupId: Int? = null,
    permissionId: Int? = null
  ) : this() {
    this.id = id
    this.objectPk = objectPk
    this.contentTypeId = contentTypeId
    this.groupId = groupId
    this.permissionId = permissionId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised GuardianGroupobjectpermissionRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.GuardianGroupobjectpermission?) : this() {
    if (value != null) {
      this.id = value.id
      this.objectPk = value.objectPk
      this.contentTypeId = value.contentTypeId
      this.groupId = value.groupId
      this.permissionId = value.permissionId
      resetChangedOnNotNull()
    }
  }
}
