/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PaperlessMailProcessedmailRecord() :
  UpdatableRecordImpl<PaperlessMailProcessedmailRecord>(com.functionaldude.paperless.jooq.`public`.tables.PaperlessMailProcessedmail.PAPERLESS_MAIL_PROCESSEDMAIL) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var folder: String?
    set(value): Unit = set(1, value)
    get(): String? = get(1) as String?

  open var uid: String?
    set(value): Unit = set(2, value)
    get(): String? = get(2) as String?

  open var subject: String?
    set(value): Unit = set(3, value)
    get(): String? = get(3) as String?

  open var received: OffsetDateTime?
    set(value): Unit = set(4, value)
    get(): OffsetDateTime? = get(4) as OffsetDateTime?

  open var processed: OffsetDateTime?
    set(value): Unit = set(5, value)
    get(): OffsetDateTime? = get(5) as OffsetDateTime?

  open var status: String?
    set(value): Unit = set(6, value)
    get(): String? = get(6) as String?

  open var error: String?
    set(value): Unit = set(7, value)
    get(): String? = get(7) as String?

  open var ownerId: Int?
    set(value): Unit = set(8, value)
    get(): Int? = get(8) as Int?

  open var ruleId: Int?
    set(value): Unit = set(9, value)
    get(): Int? = get(9) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised PaperlessMailProcessedmailRecord
   */
  constructor(
    id: Int? = null,
    folder: String? = null,
    uid: String? = null,
    subject: String? = null,
    received: OffsetDateTime? = null,
    processed: OffsetDateTime? = null,
    status: String? = null,
    error: String? = null,
    ownerId: Int? = null,
    ruleId: Int? = null
  ) : this() {
    this.id = id
    this.folder = folder
    this.uid = uid
    this.subject = subject
    this.received = received
    this.processed = processed
    this.status = status
    this.error = error
    this.ownerId = ownerId
    this.ruleId = ruleId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised PaperlessMailProcessedmailRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.PaperlessMailProcessedmail?) : this() {
    if (value != null) {
      this.id = value.id
      this.folder = value.folder
      this.uid = value.uid
      this.subject = value.subject
      this.received = value.received
      this.processed = value.processed
      this.status = value.status
      this.error = value.error
      this.ownerId = value.ownerId
      this.ruleId = value.ruleId
      resetChangedOnNotNull()
    }
  }
}
