/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.records


import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PaperlessMailMailruleAssignTagsRecord() :
  UpdatableRecordImpl<PaperlessMailMailruleAssignTagsRecord>(com.functionaldude.paperless.jooq.`public`.tables.PaperlessMailMailruleAssignTags.PAPERLESS_MAIL_MAILRULE_ASSIGN_TAGS) {

  open var id: Int?
    set(value): Unit = set(0, value)
    get(): Int? = get(0) as Int?

  open var mailruleId: Int?
    set(value): Unit = set(1, value)
    get(): Int? = get(1) as Int?

  open var tagId: Int?
    set(value): Unit = set(2, value)
    get(): Int? = get(2) as Int?

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override fun key(): Record1<Int?> = super.key() as Record1<Int?>

  /**
   * Create a detached, initialised PaperlessMailMailruleAssignTagsRecord
   */
  constructor(id: Int? = null, mailruleId: Int? = null, tagId: Int? = null) : this() {
    this.id = id
    this.mailruleId = mailruleId
    this.tagId = tagId
    resetChangedOnNotNull()
  }

  /**
   * Create a detached, initialised PaperlessMailMailruleAssignTagsRecord
   */
  constructor(value: com.functionaldude.paperless.jooq.`public`.tables.pojos.PaperlessMailMailruleAssignTags?) : this() {
    if (value != null) {
      this.id = value.id
      this.mailruleId = value.mailruleId
      this.tagId = value.tagId
      resetChangedOnNotNull()
    }
  }
}
