/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.paperless_rag


import com.functionaldude.paperless.jooq.DefaultCatalog
import com.functionaldude.paperless.jooq.paperless_rag.tables.DocumentChunk
import com.functionaldude.paperless.jooq.paperless_rag.tables.DocumentSource
import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class PaperlessRag : SchemaImpl("paperless_rag", DefaultCatalog.DEFAULT_CATALOG) {
  companion object {

    /**
     * The reference instance of <code>paperless_rag</code>
     */
    val PAPERLESS_RAG: PaperlessRag = PaperlessRag()
  }

  /**
   * The table <code>paperless_rag.document_chunk</code>.
   */
  val DOCUMENT_CHUNK: DocumentChunk get() = DocumentChunk.DOCUMENT_CHUNK

  /**
   * The table <code>paperless_rag.document_source</code>.
   */
  val DOCUMENT_SOURCE: DocumentSource get() = DocumentSource.DOCUMENT_SOURCE

  override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

  override fun getTables(): List<Table<*>> = listOf(
    DocumentChunk.DOCUMENT_CHUNK,
    DocumentSource.DOCUMENT_SOURCE
  )
}
