/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.paperless_rag.tables.pojos


import java.io.Serializable
import java.time.LocalDate
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DocumentSource(
  val id: Long? = null,
  val paperlessDocId: Int? = null,
  val title: String? = null,
  val correspondent: String? = null,
  val docDate: LocalDate? = null,
  val paperlessModifiedAt: OffsetDateTime? = null,
  val lastIngestedAt: OffsetDateTime? = null,
  val status: String? = null,
  val errorMessage: String? = null,
  val createdAt: OffsetDateTime? = null,
  val updatedAt: OffsetDateTime? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: DocumentSource = other as DocumentSource
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.paperlessDocId == null) {
      if (o.paperlessDocId != null)
        return false
    } else if (this.paperlessDocId != o.paperlessDocId)
      return false
    if (this.title == null) {
      if (o.title != null)
        return false
    } else if (this.title != o.title)
      return false
    if (this.correspondent == null) {
      if (o.correspondent != null)
        return false
    } else if (this.correspondent != o.correspondent)
      return false
    if (this.docDate == null) {
      if (o.docDate != null)
        return false
    } else if (this.docDate != o.docDate)
      return false
    if (this.paperlessModifiedAt == null) {
      if (o.paperlessModifiedAt != null)
        return false
    } else if (this.paperlessModifiedAt != o.paperlessModifiedAt)
      return false
    if (this.lastIngestedAt == null) {
      if (o.lastIngestedAt != null)
        return false
    } else if (this.lastIngestedAt != o.lastIngestedAt)
      return false
    if (this.status == null) {
      if (o.status != null)
        return false
    } else if (this.status != o.status)
      return false
    if (this.errorMessage == null) {
      if (o.errorMessage != null)
        return false
    } else if (this.errorMessage != o.errorMessage)
      return false
    if (this.createdAt == null) {
      if (o.createdAt != null)
        return false
    } else if (this.createdAt != o.createdAt)
      return false
    if (this.updatedAt == null) {
      if (o.updatedAt != null)
        return false
    } else if (this.updatedAt != o.updatedAt)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.paperlessDocId == null) 0 else this.paperlessDocId.hashCode())
    result = prime * result + (if (this.title == null) 0 else this.title.hashCode())
    result = prime * result + (if (this.correspondent == null) 0 else this.correspondent.hashCode())
    result = prime * result + (if (this.docDate == null) 0 else this.docDate.hashCode())
    result = prime * result + (if (this.paperlessModifiedAt == null) 0 else this.paperlessModifiedAt.hashCode())
    result = prime * result + (if (this.lastIngestedAt == null) 0 else this.lastIngestedAt.hashCode())
    result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
    result = prime * result + (if (this.errorMessage == null) 0 else this.errorMessage.hashCode())
    result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
    result = prime * result + (if (this.updatedAt == null) 0 else this.updatedAt.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("DocumentSource (")

    sb.append(id)
    sb.append(", ").append(paperlessDocId)
    sb.append(", ").append(title)
    sb.append(", ").append(correspondent)
    sb.append(", ").append(docDate)
    sb.append(", ").append(paperlessModifiedAt)
    sb.append(", ").append(lastIngestedAt)
    sb.append(", ").append(status)
    sb.append(", ").append(errorMessage)
    sb.append(", ").append(createdAt)
    sb.append(", ").append(updatedAt)

    sb.append(")")
    return sb.toString()
  }
}
