/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.paperless_rag.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Oauth2AuthorizationConsent(
  val registeredClientId: String? = null,
  val principalName: String? = null,
  val authorities: String? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: Oauth2AuthorizationConsent = other as Oauth2AuthorizationConsent
    if (this.registeredClientId == null) {
      if (o.registeredClientId != null)
        return false
    } else if (this.registeredClientId != o.registeredClientId)
      return false
    if (this.principalName == null) {
      if (o.principalName != null)
        return false
    } else if (this.principalName != o.principalName)
      return false
    if (this.authorities == null) {
      if (o.authorities != null)
        return false
    } else if (this.authorities != o.authorities)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.registeredClientId == null) 0 else this.registeredClientId.hashCode())
    result = prime * result + (if (this.principalName == null) 0 else this.principalName.hashCode())
    result = prime * result + (if (this.authorities == null) 0 else this.authorities.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("Oauth2AuthorizationConsent (")

    sb.append(registeredClientId)
    sb.append(", ").append(principalName)
    sb.append(", ").append(authorities)

    sb.append(")")
    return sb.toString()
  }
}
