/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


@Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
@Suppress("UNCHECKED_CAST")
open class Halfvec : AbstractRoutine<Any>(
  "halfvec",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  DefaultDataType.getDefaultDataType("\"public\".\"halfvec\"")
) {
  companion object {
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val RETURN_VALUE: Parameter<Any?> = Internal.createParameter(
      "RETURN_VALUE",
      DefaultDataType.getDefaultDataType("\"public\".\"halfvec\""),
      false,
      false
    )

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _1: Parameter<Any?> =
      Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"halfvec\""), false, true)

    /**
     * The parameter <code>public.halfvec._2</code>.
     */
    val _2: Parameter<Int?> = Internal.createParameter("_2", SQLDataType.INTEGER, false, true)

    /**
     * The parameter <code>public.halfvec._3</code>.
     */
    val _3: Parameter<Boolean?> = Internal.createParameter("_3", SQLDataType.BOOLEAN, false, true)
  }

  init {
    returnParameter = Halfvec.RETURN_VALUE
    addInParameter(Halfvec._1)
    addInParameter(Halfvec._2)
    addInParameter(Halfvec._3)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Any?): Unit = setValue(Halfvec._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Any?>): Halfvec {
    setField(Halfvec._1, field)
    return this
  }

  /**
   * Set the <code>_2</code> parameter IN value to the routine
   */
  fun set__2(value: Int?): Unit = setValue(Halfvec._2, value)

  /**
   * Set the <code>_2</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__2(field: Field<Int?>): Halfvec {
    setField(Halfvec._2, field)
    return this
  }

  /**
   * Set the <code>_3</code> parameter IN value to the routine
   */
  fun set__3(value: Boolean?): Unit = setValue(Halfvec._3, value)

  /**
   * Set the <code>_3</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__3(field: Field<Boolean?>): Halfvec {
    setField(Halfvec._3, field)
    return this
  }
}
