/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class HalfvecTypmodIn : AbstractRoutine<Int>(
  "halfvec_typmod_in",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  SQLDataType.INTEGER
) {
  companion object {

    /**
     * The parameter <code>public.halfvec_typmod_in.RETURN_VALUE</code>.
     */
    val RETURN_VALUE: Parameter<Int?> = Internal.createParameter("RETURN_VALUE", SQLDataType.INTEGER, false, false)

    /**
     * The parameter <code>public.halfvec_typmod_in._1</code>.
     */
    val _1: Parameter<Array<Any?>?> = Internal.createParameter(
      "_1",
      DefaultDataType.getDefaultDataType("\"pg_catalog\".\"cstring\"").array(),
      false,
      true
    )
  }

  init {
    returnParameter = HalfvecTypmodIn.RETURN_VALUE
    addInParameter(HalfvecTypmodIn._1)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Array<Any?>?): Unit = setValue(HalfvecTypmodIn._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Array<Any?>?>): HalfvecTypmodIn {
    setField(HalfvecTypmodIn._1, field)
    return this
  }
}
