/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class HammingDistance : AbstractRoutine<Double>(
  "hamming_distance",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  SQLDataType.DOUBLE
) {
  companion object {

    /**
     * The parameter <code>public.hamming_distance.RETURN_VALUE</code>.
     */
    val RETURN_VALUE: Parameter<Double?> = Internal.createParameter("RETURN_VALUE", SQLDataType.DOUBLE, false, false)

    /**
     * The parameter <code>public.hamming_distance._1</code>.
     */
    val _1: Parameter<String?> = Internal.createParameter("_1", SQLDataType.CHAR, false, true)

    /**
     * The parameter <code>public.hamming_distance._2</code>.
     */
    val _2: Parameter<String?> = Internal.createParameter("_2", SQLDataType.CHAR, false, true)
  }

  init {
    returnParameter = HammingDistance.RETURN_VALUE
    addInParameter(HammingDistance._1)
    addInParameter(HammingDistance._2)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: String?): Unit = setValue(HammingDistance._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<String?>): HammingDistance {
    setField(HammingDistance._1, field)
    return this
  }

  /**
   * Set the <code>_2</code> parameter IN value to the routine
   */
  fun set__2(value: String?): Unit = setValue(HammingDistance._2, value)

  /**
   * Set the <code>_2</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__2(field: Field<String?>): HammingDistance {
    setField(HammingDistance._2, field)
    return this
  }
}
