/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal


@Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
@Suppress("UNCHECKED_CAST")
open class L2Normalize1 : AbstractRoutine<Any>(
  "l2_normalize",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  DefaultDataType.getDefaultDataType("\"public\".\"vector\"")
) {
  companion object {
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val RETURN_VALUE: Parameter<Any?> = Internal.createParameter(
      "RETURN_VALUE",
      DefaultDataType.getDefaultDataType("\"public\".\"vector\""),
      false,
      false
    )

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _1: Parameter<Any?> =
      Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"vector\""), false, true)
  }

  init {
    returnParameter = L2Normalize1.RETURN_VALUE
    addInParameter(L2Normalize1._1)
    setOverloaded(true)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Any?): Unit = setValue(L2Normalize1._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Any?>): L2Normalize1 {
    setField(L2Normalize1._1, field)
    return this
  }
}
