/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


@Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
@Suppress("UNCHECKED_CAST")
open class SparsevecIn : AbstractRoutine<Any>(
  "sparsevec_in",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  DefaultDataType.getDefaultDataType("\"public\".\"sparsevec\"")
) {
  companion object {
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val RETURN_VALUE: Parameter<Any?> = Internal.createParameter(
      "RETURN_VALUE",
      DefaultDataType.getDefaultDataType("\"public\".\"sparsevec\""),
      false,
      false
    )

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _1: Parameter<Any?> =
      Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"pg_catalog\".\"cstring\""), false, true)

    /**
     * The parameter <code>public.sparsevec_in._2</code>.
     */
    val _2: Parameter<Long?> = Internal.createParameter("_2", SQLDataType.BIGINT, false, true)

    /**
     * The parameter <code>public.sparsevec_in._3</code>.
     */
    val _3: Parameter<Int?> = Internal.createParameter("_3", SQLDataType.INTEGER, false, true)
  }

  init {
    returnParameter = SparsevecIn.RETURN_VALUE
    addInParameter(SparsevecIn._1)
    addInParameter(SparsevecIn._2)
    addInParameter(SparsevecIn._3)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Any?): Unit = setValue(SparsevecIn._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Any?>): SparsevecIn {
    setField(SparsevecIn._1, field)
    return this
  }

  /**
   * Set the <code>_2</code> parameter IN value to the routine
   */
  fun set__2(value: Long?): Unit = setValue(SparsevecIn._2, value)

  /**
   * Set the <code>_2</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__2(field: Field<Long?>): SparsevecIn {
    setField(SparsevecIn._2, field)
    return this
  }

  /**
   * Set the <code>_3</code> parameter IN value to the routine
   */
  fun set__3(value: Int?): Unit = setValue(SparsevecIn._3, value)

  /**
   * Set the <code>_3</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__3(field: Field<Int?>): SparsevecIn {
    setField(SparsevecIn._3, field)
    return this
  }
}
