/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class VectorNe :
  AbstractRoutine<Boolean>("vector_ne", com.functionaldude.paperless.jooq.`public`.Public.PUBLIC, SQLDataType.BOOLEAN) {
  companion object {

    /**
     * The parameter <code>public.vector_ne.RETURN_VALUE</code>.
     */
    val RETURN_VALUE: Parameter<Boolean?> = Internal.createParameter("RETURN_VALUE", SQLDataType.BOOLEAN, false, false)

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _1: Parameter<Any?> =
      Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"vector\""), false, true)

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _2: Parameter<Any?> =
      Internal.createParameter("_2", DefaultDataType.getDefaultDataType("\"public\".\"vector\""), false, true)
  }

  init {
    returnParameter = VectorNe.RETURN_VALUE
    addInParameter(VectorNe._1)
    addInParameter(VectorNe._2)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Any?): Unit = setValue(VectorNe._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Any?>): VectorNe {
    setField(VectorNe._1, field)
    return this
  }

  /**
   * Set the <code>_2</code> parameter IN value to the routine
   */
  fun set__2(value: Any?): Unit = setValue(VectorNe._2, value)

  /**
   * Set the <code>_2</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__2(field: Field<Any?>): VectorNe {
    setField(VectorNe._2, field)
    return this
  }
}
