/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.routines


import org.jooq.Field
import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DefaultDataType
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


@Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
@Suppress("UNCHECKED_CAST")
open class VectorToSparsevec : AbstractRoutine<Any>(
  "vector_to_sparsevec",
  com.functionaldude.paperless.jooq.`public`.Public.PUBLIC,
  DefaultDataType.getDefaultDataType("\"public\".\"sparsevec\"")
) {
  companion object {
    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val RETURN_VALUE: Parameter<Any?> = Internal.createParameter(
      "RETURN_VALUE",
      DefaultDataType.getDefaultDataType("\"public\".\"sparsevec\""),
      false,
      false
    )

    @Deprecated(message = "Unknown data type. If this is a qualified, user-defined type, it may have been excluded from code generation. If this is a built-in type, you can define an explicit org.jooq.Binding to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.")
    val _1: Parameter<Any?> =
      Internal.createParameter("_1", DefaultDataType.getDefaultDataType("\"public\".\"vector\""), false, true)

    /**
     * The parameter <code>public.vector_to_sparsevec._2</code>.
     */
    val _2: Parameter<Int?> = Internal.createParameter("_2", SQLDataType.INTEGER, false, true)

    /**
     * The parameter <code>public.vector_to_sparsevec._3</code>.
     */
    val _3: Parameter<Boolean?> = Internal.createParameter("_3", SQLDataType.BOOLEAN, false, true)
  }

  init {
    returnParameter = VectorToSparsevec.RETURN_VALUE
    addInParameter(VectorToSparsevec._1)
    addInParameter(VectorToSparsevec._2)
    addInParameter(VectorToSparsevec._3)
  }

  /**
   * Set the <code>_1</code> parameter IN value to the routine
   */
  fun set__1(value: Any?): Unit = setValue(VectorToSparsevec._1, value)

  /**
   * Set the <code>_1</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__1(field: Field<Any?>): VectorToSparsevec {
    setField(VectorToSparsevec._1, field)
    return this
  }

  /**
   * Set the <code>_2</code> parameter IN value to the routine
   */
  fun set__2(value: Int?): Unit = setValue(VectorToSparsevec._2, value)

  /**
   * Set the <code>_2</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__2(field: Field<Int?>): VectorToSparsevec {
    setField(VectorToSparsevec._2, field)
    return this
  }

  /**
   * Set the <code>_3</code> parameter IN value to the routine
   */
  fun set__3(value: Boolean?): Unit = setValue(VectorToSparsevec._3, value)

  /**
   * Set the <code>_3</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  fun set__3(field: Field<Boolean?>): VectorToSparsevec {
    setField(VectorToSparsevec._3, field)
    return this
  }
}
