/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AuthUserUserPermissions(
  val id: Int? = null,
  val userId: Int? = null,
  val permissionId: Int? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: AuthUserUserPermissions = other as AuthUserUserPermissions
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.userId == null) {
      if (o.userId != null)
        return false
    } else if (this.userId != o.userId)
      return false
    if (this.permissionId == null) {
      if (o.permissionId != null)
        return false
    } else if (this.permissionId != o.permissionId)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.userId == null) 0 else this.userId.hashCode())
    result = prime * result + (if (this.permissionId == null) 0 else this.permissionId.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("AuthUserUserPermissions (")

    sb.append(id)
    sb.append(", ").append(userId)
    sb.append(", ").append(permissionId)

    sb.append(")")
    return sb.toString()
  }
}
