/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class AuthPermission(
  val id: Int? = null,
  val name: String? = null,
  val contentTypeId: Int? = null,
  val codename: String? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: AuthPermission = other as AuthPermission
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.name == null) {
      if (o.name != null)
        return false
    } else if (this.name != o.name)
      return false
    if (this.contentTypeId == null) {
      if (o.contentTypeId != null)
        return false
    } else if (this.contentTypeId != o.contentTypeId)
      return false
    if (this.codename == null) {
      if (o.codename != null)
        return false
    } else if (this.codename != o.codename)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
    result = prime * result + (if (this.contentTypeId == null) 0 else this.contentTypeId.hashCode())
    result = prime * result + (if (this.codename == null) 0 else this.codename.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("AuthPermission (")

    sb.append(id)
    sb.append(", ").append(name)
    sb.append(", ").append(contentTypeId)
    sb.append(", ").append(codename)

    sb.append(")")
    return sb.toString()
  }
}
