/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DjangoSession(
  val sessionKey: String? = null,
  val sessionData: String? = null,
  val expireDate: OffsetDateTime? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: DjangoSession = other as DjangoSession
    if (this.sessionKey == null) {
      if (o.sessionKey != null)
        return false
    } else if (this.sessionKey != o.sessionKey)
      return false
    if (this.sessionData == null) {
      if (o.sessionData != null)
        return false
    } else if (this.sessionData != o.sessionData)
      return false
    if (this.expireDate == null) {
      if (o.expireDate != null)
        return false
    } else if (this.expireDate != o.expireDate)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.sessionKey == null) 0 else this.sessionKey.hashCode())
    result = prime * result + (if (this.sessionData == null) 0 else this.sessionData.hashCode())
    result = prime * result + (if (this.expireDate == null) 0 else this.expireDate.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("DjangoSession (")

    sb.append(sessionKey)
    sb.append(", ").append(sessionData)
    sb.append(", ").append(expireDate)

    sb.append(")")
    return sb.toString()
  }
}
