/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DjangoMigrations(
  val id: Int? = null,
  val app: String? = null,
  val name: String? = null,
  val applied: OffsetDateTime? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: DjangoMigrations = other as DjangoMigrations
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.app == null) {
      if (o.app != null)
        return false
    } else if (this.app != o.app)
      return false
    if (this.name == null) {
      if (o.name != null)
        return false
    } else if (this.name != o.name)
      return false
    if (this.applied == null) {
      if (o.applied != null)
        return false
    } else if (this.applied != o.applied)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.app == null) 0 else this.app.hashCode())
    result = prime * result + (if (this.name == null) 0 else this.name.hashCode())
    result = prime * result + (if (this.applied == null) 0 else this.applied.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("DjangoMigrations (")

    sb.append(id)
    sb.append(", ").append(app)
    sb.append(", ").append(name)
    sb.append(", ").append(applied)

    sb.append(")")
    return sb.toString()
  }
}
