/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime
import java.util.*


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DocumentsWorkflowrun(
  val id: Int? = null,
  val type: Int? = null,
  val runAt: OffsetDateTime? = null,
  val documentId: Int? = null,
  val workflowId: Int? = null,
  val deletedAt: OffsetDateTime? = null,
  val restoredAt: OffsetDateTime? = null,
  val transactionId: UUID? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: DocumentsWorkflowrun = other as DocumentsWorkflowrun
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.type == null) {
      if (o.type != null)
        return false
    } else if (this.type != o.type)
      return false
    if (this.runAt == null) {
      if (o.runAt != null)
        return false
    } else if (this.runAt != o.runAt)
      return false
    if (this.documentId == null) {
      if (o.documentId != null)
        return false
    } else if (this.documentId != o.documentId)
      return false
    if (this.workflowId == null) {
      if (o.workflowId != null)
        return false
    } else if (this.workflowId != o.workflowId)
      return false
    if (this.deletedAt == null) {
      if (o.deletedAt != null)
        return false
    } else if (this.deletedAt != o.deletedAt)
      return false
    if (this.restoredAt == null) {
      if (o.restoredAt != null)
        return false
    } else if (this.restoredAt != o.restoredAt)
      return false
    if (this.transactionId == null) {
      if (o.transactionId != null)
        return false
    } else if (this.transactionId != o.transactionId)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.type == null) 0 else this.type.hashCode())
    result = prime * result + (if (this.runAt == null) 0 else this.runAt.hashCode())
    result = prime * result + (if (this.documentId == null) 0 else this.documentId.hashCode())
    result = prime * result + (if (this.workflowId == null) 0 else this.workflowId.hashCode())
    result = prime * result + (if (this.deletedAt == null) 0 else this.deletedAt.hashCode())
    result = prime * result + (if (this.restoredAt == null) 0 else this.restoredAt.hashCode())
    result = prime * result + (if (this.transactionId == null) 0 else this.transactionId.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("DocumentsWorkflowrun (")

    sb.append(id)
    sb.append(", ").append(type)
    sb.append(", ").append(runAt)
    sb.append(", ").append(documentId)
    sb.append(", ").append(workflowId)
    sb.append(", ").append(deletedAt)
    sb.append(", ").append(restoredAt)
    sb.append(", ").append(transactionId)

    sb.append(")")
    return sb.toString()
  }
}
