/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class DocumentsPaperlesstask(
  val id: Int? = null,
  val taskId: String? = null,
  val acknowledged: Boolean? = null,
  val dateCreated: OffsetDateTime? = null,
  val dateDone: OffsetDateTime? = null,
  val dateStarted: OffsetDateTime? = null,
  val result: String? = null,
  val status: String? = null,
  val taskName: String? = null,
  val taskFileName: String? = null,
  val ownerId: Int? = null,
  val type: String? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: DocumentsPaperlesstask = other as DocumentsPaperlesstask
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.taskId == null) {
      if (o.taskId != null)
        return false
    } else if (this.taskId != o.taskId)
      return false
    if (this.acknowledged == null) {
      if (o.acknowledged != null)
        return false
    } else if (this.acknowledged != o.acknowledged)
      return false
    if (this.dateCreated == null) {
      if (o.dateCreated != null)
        return false
    } else if (this.dateCreated != o.dateCreated)
      return false
    if (this.dateDone == null) {
      if (o.dateDone != null)
        return false
    } else if (this.dateDone != o.dateDone)
      return false
    if (this.dateStarted == null) {
      if (o.dateStarted != null)
        return false
    } else if (this.dateStarted != o.dateStarted)
      return false
    if (this.result == null) {
      if (o.result != null)
        return false
    } else if (this.result != o.result)
      return false
    if (this.status == null) {
      if (o.status != null)
        return false
    } else if (this.status != o.status)
      return false
    if (this.taskName == null) {
      if (o.taskName != null)
        return false
    } else if (this.taskName != o.taskName)
      return false
    if (this.taskFileName == null) {
      if (o.taskFileName != null)
        return false
    } else if (this.taskFileName != o.taskFileName)
      return false
    if (this.ownerId == null) {
      if (o.ownerId != null)
        return false
    } else if (this.ownerId != o.ownerId)
      return false
    if (this.type == null) {
      if (o.type != null)
        return false
    } else if (this.type != o.type)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.taskId == null) 0 else this.taskId.hashCode())
    result = prime * result + (if (this.acknowledged == null) 0 else this.acknowledged.hashCode())
    result = prime * result + (if (this.dateCreated == null) 0 else this.dateCreated.hashCode())
    result = prime * result + (if (this.dateDone == null) 0 else this.dateDone.hashCode())
    result = prime * result + (if (this.dateStarted == null) 0 else this.dateStarted.hashCode())
    result = prime * result + (if (this.result == null) 0 else this.result.hashCode())
    result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
    result = prime * result + (if (this.taskName == null) 0 else this.taskName.hashCode())
    result = prime * result + (if (this.taskFileName == null) 0 else this.taskFileName.hashCode())
    result = prime * result + (if (this.ownerId == null) 0 else this.ownerId.hashCode())
    result = prime * result + (if (this.type == null) 0 else this.type.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("DocumentsPaperlesstask (")

    sb.append(id)
    sb.append(", ").append(taskId)
    sb.append(", ").append(acknowledged)
    sb.append(", ").append(dateCreated)
    sb.append(", ").append(dateDone)
    sb.append(", ").append(dateStarted)
    sb.append(", ").append(result)
    sb.append(", ").append(status)
    sb.append(", ").append(taskName)
    sb.append(", ").append(taskFileName)
    sb.append(", ").append(ownerId)
    sb.append(", ").append(type)

    sb.append(")")
    return sb.toString()
  }
}
