/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class PaperlessMailProcessedmail(
  val id: Int? = null,
  val folder: String? = null,
  val uid: String? = null,
  val subject: String? = null,
  val received: OffsetDateTime? = null,
  val processed: OffsetDateTime? = null,
  val status: String? = null,
  val error: String? = null,
  val ownerId: Int? = null,
  val ruleId: Int? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: PaperlessMailProcessedmail = other as PaperlessMailProcessedmail
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.folder == null) {
      if (o.folder != null)
        return false
    } else if (this.folder != o.folder)
      return false
    if (this.uid == null) {
      if (o.uid != null)
        return false
    } else if (this.uid != o.uid)
      return false
    if (this.subject == null) {
      if (o.subject != null)
        return false
    } else if (this.subject != o.subject)
      return false
    if (this.received == null) {
      if (o.received != null)
        return false
    } else if (this.received != o.received)
      return false
    if (this.processed == null) {
      if (o.processed != null)
        return false
    } else if (this.processed != o.processed)
      return false
    if (this.status == null) {
      if (o.status != null)
        return false
    } else if (this.status != o.status)
      return false
    if (this.error == null) {
      if (o.error != null)
        return false
    } else if (this.error != o.error)
      return false
    if (this.ownerId == null) {
      if (o.ownerId != null)
        return false
    } else if (this.ownerId != o.ownerId)
      return false
    if (this.ruleId == null) {
      if (o.ruleId != null)
        return false
    } else if (this.ruleId != o.ruleId)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.folder == null) 0 else this.folder.hashCode())
    result = prime * result + (if (this.uid == null) 0 else this.uid.hashCode())
    result = prime * result + (if (this.subject == null) 0 else this.subject.hashCode())
    result = prime * result + (if (this.received == null) 0 else this.received.hashCode())
    result = prime * result + (if (this.processed == null) 0 else this.processed.hashCode())
    result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
    result = prime * result + (if (this.error == null) 0 else this.error.hashCode())
    result = prime * result + (if (this.ownerId == null) 0 else this.ownerId.hashCode())
    result = prime * result + (if (this.ruleId == null) 0 else this.ruleId.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("PaperlessMailProcessedmail (")

    sb.append(id)
    sb.append(", ").append(folder)
    sb.append(", ").append(uid)
    sb.append(", ").append(subject)
    sb.append(", ").append(received)
    sb.append(", ").append(processed)
    sb.append(", ").append(status)
    sb.append(", ").append(error)
    sb.append(", ").append(ownerId)
    sb.append(", ").append(ruleId)

    sb.append(")")
    return sb.toString()
  }
}
