/*
 * This file is generated by jOOQ.
 */
package com.functionaldude.paperless.jooq.`public`.tables.pojos


import java.io.Serializable
import java.time.OffsetDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class SocialaccountSocialtoken(
  val id: Int? = null,
  val token: String? = null,
  val tokenSecret: String? = null,
  val expiresAt: OffsetDateTime? = null,
  val accountId: Int? = null,
  val appId: Int? = null
) : Serializable {

  override fun equals(other: Any?): Boolean {
    if (this === other)
      return true
    if (other == null)
      return false
    if (this::class != other::class)
      return false
    val o: SocialaccountSocialtoken = other as SocialaccountSocialtoken
    if (this.id == null) {
      if (o.id != null)
        return false
    } else if (this.id != o.id)
      return false
    if (this.token == null) {
      if (o.token != null)
        return false
    } else if (this.token != o.token)
      return false
    if (this.tokenSecret == null) {
      if (o.tokenSecret != null)
        return false
    } else if (this.tokenSecret != o.tokenSecret)
      return false
    if (this.expiresAt == null) {
      if (o.expiresAt != null)
        return false
    } else if (this.expiresAt != o.expiresAt)
      return false
    if (this.accountId == null) {
      if (o.accountId != null)
        return false
    } else if (this.accountId != o.accountId)
      return false
    if (this.appId == null) {
      if (o.appId != null)
        return false
    } else if (this.appId != o.appId)
      return false
    return true
  }

  override fun hashCode(): Int {
    val prime = 31
    var result = 1
    result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
    result = prime * result + (if (this.token == null) 0 else this.token.hashCode())
    result = prime * result + (if (this.tokenSecret == null) 0 else this.tokenSecret.hashCode())
    result = prime * result + (if (this.expiresAt == null) 0 else this.expiresAt.hashCode())
    result = prime * result + (if (this.accountId == null) 0 else this.accountId.hashCode())
    result = prime * result + (if (this.appId == null) 0 else this.appId.hashCode())
    return result
  }

  override fun toString(): String {
    val sb = StringBuilder("SocialaccountSocialtoken (")

    sb.append(id)
    sb.append(", ").append(token)
    sb.append(", ").append(tokenSecret)
    sb.append(", ").append(expiresAt)
    sb.append(", ").append(accountId)
    sb.append(", ").append(appId)

    sb.append(")")
    return sb.toString()
  }
}
